//! Typed IPC surface: command registry, event registry and binding export.
//!
//! `src/bindings.ts` is generated from this registry and **committed** to the
//! repository, so the frontend can be type-checked without first building the
//! Rust side. `tests/ipc.rs` asserts the committed file matches the registry;
//! run `DEVX_UPDATE_BINDINGS=1 cargo test -p devx-desktop` to refresh it.

use std::path::Path;

use tauri_specta::{collect_commands, collect_events};

use crate::{commands, events};

/// Path of the generated TypeScript client, relative to `src-tauri`.
pub const BINDINGS_PATH: &str = "../src/bindings.ts";

/// Builds the `tauri-specta` builder holding every command and event.
///
/// Keeping this in one function means the exported bindings and the runtime
/// invoke handler can never disagree about what exists.
pub fn builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            commands::app_info,
            commands::paths_get,
            commands::config_get,
            commands::config_set,
            commands::config_reset,
            commands::config_export,
            commands::config_import,
            commands::doctor_run,
            commands::catalog_list,
            commands::component_versions,
            commands::component_install,
            commands::component_uninstall,
            commands::installed_versions,
            commands::service_component_ids,
            commands::service_start,
            commands::service_stop,
            commands::service_status,
            commands::service_logs,
            commands::service_metrics,
            commands::logs_list,
            commands::logs_read,
            commands::php_pool_list,
            commands::php_pool_start,
            commands::php_pool_stop,
            commands::php_pool_status,
            commands::php_pool_logs,
            commands::php_ext_list,
            commands::php_ext_set,
            commands::site_list,
            commands::site_add,
            commands::site_remove,
            commands::site_env_set,
            commands::site_env_delete,
            commands::ca_status,
            commands::ca_install,
            commands::ca_remove,
            commands::dns_status,
            commands::dns_start,
            commands::dns_stop,
            commands::db_list_servers,
            commands::db_query,
            commands::db_list_databases,
            commands::db_list_tables,
            commands::backup_list,
            commands::backup_create,
            commands::backup_restore,
            commands::backup_delete,
            commands::mail_status,
            commands::mail_list,
            commands::mail_message,
            commands::mail_delete,
            commands::tunnel_start,
            commands::tunnel_stop,
            commands::tunnel_status,
            commands::worker_list,
            commands::worker_add,
            commands::worker_remove,
            commands::worker_start,
            commands::worker_stop,
            commands::privileged_status,
            commands::reveal_managed_dir,
            commands::settings_sync_autostart,
            commands::update_check,
            commands::terminal_run,
            commands::terminal_path,
            commands::template_list,
            commands::template_create,
            commands::site_alias_add,
            commands::site_alias_delete,
            commands::cron_list,
            commands::cron_set,
            commands::cron_delete,
        ])
        .events(collect_events![
            events::InstallProgress,
            events::ServiceEventUpdate,
            events::TerminalOutput
        ])
}

/// Writes the TypeScript client for `builder` to `path`.
pub fn export_bindings_to(
    builder: &tauri_specta::Builder<tauri::Wry>,
    path: impl AsRef<Path>,
) -> Result<(), String> {
    use specta_typescript::Typescript;

    let config = Typescript::default().header(
        "// Generated by tauri-specta from apps/desktop/src-tauri/src/ipc.rs.\n// Do not edit by hand: run `cargo test -p devx-desktop` to verify.\n",
    );

    builder
        .export(config, path)
        .map_err(|err| format!("failed to export TypeScript bindings: {err}"))
}

/// Refreshes the committed `src/bindings.ts`.
///
/// Debug builds only: a packaged release must never write into a source tree.
#[cfg(debug_assertions)]
pub fn export_bindings(builder: &tauri_specta::Builder<tauri::Wry>) -> Result<(), String> {
    export_bindings_to(builder, BINDINGS_PATH)
}
