// Generated by tauri-specta from apps/desktop/src-tauri/src/ipc.rs.
// Do not edit by hand: run `cargo test -p devx-desktop` to verify.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Returns metadata about the running DevX build. */
	appInfo: () => typedError<AppInfo, DevxError>(__TAURI_INVOKE("app_info")),
	/**  Returns the resolved configuration and data directories. */
	pathsGet: () => typedError<AppPaths, DevxError>(__TAURI_INVOKE("paths_get")),
	/**  Returns the current configuration. */
	configGet: () => typedError<Config, DevxError>(__TAURI_INVOKE("config_get")),
	/**
	 *  Validates and persists a replacement configuration.
	 * 
	 *  Returns the stored configuration, which may differ from the input where
	 *  DevX normalises values such as `schema_version`.
	 */
	configSet: (config: Config) => typedError<Config, DevxError>(__TAURI_INVOKE("config_set", { config })),
	/**  Restores the default configuration. */
	configReset: () => typedError<Config, DevxError>(__TAURI_INVOKE("config_reset")),
	/**  Runs environment diagnostics against the live system. */
	doctorRun: () => typedError<DoctorReport, DevxError>(__TAURI_INVOKE("doctor_run")),
	/**  Lists the components DevX can install. */
	catalogList: () => typedError<ComponentSummary[], DevxError>(__TAURI_INVOKE("catalog_list")),
	/**
	 *  Lists the installable versions of one component.
	 * 
	 *  Hits the component's upstream through a revalidating cache, so repeated calls
	 *  are cheap and a network failure returns the last known list marked stale
	 *  rather than an error.
	 */
	componentVersions: (componentId: string) => typedError<VersionListing, DevxError>(__TAURI_INVOKE("component_versions", { componentId })),
	/**
	 *  Installs a component version, emitting [`InstallProgress`] events.
	 * 
	 *  Returns the install directory on success. Progress is delivered through
	 *  events keyed by component and version so the UI can update the right row.
	 */
	componentInstall: (componentId: string, version: string) => typedError<string, DevxError>(__TAURI_INVOKE("component_install", { componentId, version })),
	/**  Removes an installed component version. */
	componentUninstall: (componentId: string, version: string) => typedError<null, DevxError>(__TAURI_INVOKE("component_uninstall", { componentId, version })),
	/**  Lists every installed component version found on disk. */
	installedVersions: () => typedError<InstalledVersion[], DevxError>(__TAURI_INVOKE("installed_versions")),
	/**  Lists the component ids that DevX can supervise as background services. */
	serviceComponentIds: () => typedError<string[], DevxError>(__TAURI_INVOKE("service_component_ids")),
	/**
	 *  Starts a supervised service backed by an installed component version.
	 * 
	 *  Resolves the service plan (config rendering, port allocation), runs any
	 *  pending one-time init steps, then registers and starts the supervisor.
	 *  Returns once the service is running or the start has failed.
	 */
	serviceStart: (componentId: string, version: string) => typedError<ServiceStatus, DevxError>(__TAURI_INVOKE("service_start", { componentId, version })),
	/**  Stops a running supervised service. */
	serviceStop: (id: string) => typedError<ServiceStatus, DevxError>(__TAURI_INVOKE("service_stop", { id })),
	/**  Returns the status of a supervised service. */
	serviceStatus: (id: string) => typedError<ServiceStatus, DevxError>(__TAURI_INVOKE("service_status", { id })),
	/**  Returns log lines for a service newer than `after` (0 for all retained). */
	serviceLogs: (id: string, after: number) => typedError<LogEntry[], DevxError>(__TAURI_INVOKE("service_logs", { id, after })),
	/**
	 *  Lists the PHP FastCGI pools DevX can supervise: one per installed PHP.
	 * 
	 *  Pools are planned on the fly rather than persisted, so the list always
	 *  matches what is on disk. Workers reflect the stored setting when the pool
	 *  has one, and the default otherwise.
	 */
	phpPoolList: () => typedError<PhpPoolStatus[], DevxError>(__TAURI_INVOKE("php_pool_list")),
	/**
	 *  Starts (or reports) the FastCGI pool for one installed PHP version.
	 * 
	 *  The pool keeps the port its rendered `pool.conf` claims, so restarting
	 *  DevX never renumbers existing pools. Returns once the pool is running or
	 *  the start has failed.
	 */
	phpPoolStart: (version: string, workers: number) => typedError<PhpPoolStatus, DevxError>(__TAURI_INVOKE("php_pool_start", { version, workers })),
	/**  Stops the FastCGI pool of one PHP version. */
	phpPoolStop: (version: string) => typedError<PhpPoolStatus, DevxError>(__TAURI_INVOKE("php_pool_stop", { version })),
	/**  Returns the status of one PHP pool, stopped when it has never started. */
	phpPoolStatus: (version: string) => typedError<PhpPoolStatus, DevxError>(__TAURI_INVOKE("php_pool_status", { version })),
	/**
	 *  Returns log lines for a pool newer than `after` (0 for all retained).
	 * 
	 *  Pools reuse the service log machinery; this alias keeps the UI from
	 *  reaching into service ids by hand.
	 */
	phpPoolLogs: (version: string, after: number) => typedError<LogEntry[], DevxError>(__TAURI_INVOKE("php_pool_logs", { version, after })),
	/**  Lists the configured sites with their resolved PHP endpoints. */
	siteList: () => typedError<SiteStatus[], DevxError>(__TAURI_INVOKE("site_list")),
	/**  Adds (or replaces) a site, renders its nginx block, and syncs the set. */
	siteAdd: (hostname: string, docroot: string, phpVersion: string, https: boolean) => typedError<SiteStatus[], DevxError>(__TAURI_INVOKE("site_add", { hostname, docroot, phpVersion, https })),
	/**  Removes a site, prunes its block, and syncs. */
	siteRemove: (hostname: string) => typedError<SiteStatus[], DevxError>(__TAURI_INVOKE("site_remove", { hostname })),
	/**  Reports the local CA's status: present on disk and machine-trusted. */
	caStatus: () => typedError<CaStatus, DevxError>(__TAURI_INVOKE("ca_status")),
	/**
	 *  Creates the local CA (if missing) and installs it into the machine trust
	 *  store through the privileged helper.
	 */
	caInstall: () => typedError<CaStatus, DevxError>(__TAURI_INVOKE("ca_install")),
	/**
	 *  Removes the DevX CA from the machine trust store (the on-disk CA and any
	 *  issued site certificates are left in place for a later reinstall).
	 */
	caRemove: () => typedError<CaStatus, DevxError>(__TAURI_INVOKE("ca_remove")),
	/**  Reports the bundled resolver's status and whether the NRPT rule is active. */
	dnsStatus: () => typedError<DnsStatus, DevxError>(__TAURI_INVOKE("dns_status")),
	/**
	 *  Starts the bundled DNS resolver and (through the helper) points the NRPT
	 *  rule at it. Idempotent: starting twice keeps the running instance.
	 */
	dnsStart: () => typedError<DnsStatus, DevxError>(__TAURI_INVOKE("dns_start")),
	/**  Stops the bundled resolver and removes the NRPT rule. */
	dnsStop: () => typedError<DnsStatus, DevxError>(__TAURI_INVOKE("dns_stop")),
	/**
	 *  Lists the database servers DevX supervises and their reachability.
	 * 
	 *  Ports come from each service's rendered state where available, falling
	 *  back to the definition's default port, so this works before first start
	 *  (unreachable) and after restarts (reassigned ports picked up live).
	 */
	dbListServers: () => typedError<DbServer[], DevxError>(__TAURI_INVOKE("db_list_servers")),
	/**  Runs one read-only statement against `params` and renders a grid. */
	dbQuery: (params: ConnectionParams, statement: string) => typedError<DbResult, DevxError>(__TAURI_INVOKE("db_query", { params, statement })),
	/**  Lists the databases (schemas) visible on `params`. */
	dbListDatabases: (params: ConnectionParams) => typedError<DbResult, DevxError>(__TAURI_INVOKE("db_list_databases", { params })),
	/**  Lists the tables in `params.database`. */
	dbListTables: (params: ConnectionParams) => typedError<DbResult, DevxError>(__TAURI_INVOKE("db_list_tables", { params })),
	/**  Reports whether Mailpit is running and how full its inbox is. */
	mailStatus: () => typedError<MailStatus, DevxError>(__TAURI_INVOKE("mail_status")),
	/**  Lists the newest messages in Mailpit's inbox. */
	mailList: (limit: number) => typedError<MessageSummary[], DevxError>(__TAURI_INVOKE("mail_list", { limit })),
	/**  Fetches one full message by ID. Mailpit marks it read on fetch. */
	mailMessage: (id: string) => typedError<Message, DevxError>(__TAURI_INVOKE("mail_message", { id })),
	/**  Deletes the given messages, or every message when `ids` is empty. */
	mailDelete: (ids: string[]) => typedError<null, DevxError>(__TAURI_INVOKE("mail_delete", { ids })),
	/**
	 *  Shares `hostname` publicly through a Cloudflare quick tunnel.
	 * 
	 *  The tunnel targets whichever port nginx actually serves (live allocation
	 *  or configured default), so the public URL reaches the same server block
	 *  the local `.test` host name does.
	 */
	tunnelStart: (hostname: string) => typedError<TunnelStatus, DevxError>(__TAURI_INVOKE("tunnel_start", { hostname })),
	/**  Stops the share for `hostname`, if one is running. */
	tunnelStop: (hostname: string) => typedError<TunnelStatus, DevxError>(__TAURI_INVOKE("tunnel_stop", { hostname })),
	/**
	 *  Reports the share status for `hostname`, parsing the tunnel URL from the
	 *  process's captured log output.
	 */
	tunnelStatus: (hostname: string) => typedError<TunnelStatus, DevxError>(__TAURI_INVOKE("tunnel_status", { hostname })),
	/**
	 *  Probes the privileged helper so the UI can show whether elevated
	 *  operations (hosts entries today, HTTPS and NRPT later) are possible.
	 * 
	 *  Deliberately cheap: an open-and-close of the pipe, no handshake round
	 *  trip, so it can be polled without cost.
	 */
	privilegedStatus: () => typedError<PrivilegedStatus, DevxError>(__TAURI_INVOKE("privileged_status")),
	/**
	 *  Reveals a DevX directory in File Explorer.
	 * 
	 *  Restricted to the managed directories so the command cannot be used to open
	 *  arbitrary paths from the webview.
	 */
	revealManagedDir: (path: string) => typedError<null, DevxError>(__TAURI_INVOKE("reveal_managed_dir", { path })),
	/**
	 *  Applies `general.start_with_windows` to the OS autostart entry.
	 * 
	 *  The registry key is the operating system's state, not DevX's, so it is
	 *  synced here when the user flips the toggle (and once at startup) rather
	 *  than being derived implicitly. Returns the resulting enabled state.
	 */
	settingsSyncAutostart: () => typedError<boolean, DevxError>(__TAURI_INVOKE("settings_sync_autostart")),
	/**
	 *  Checks the newest published DevX release and compares it to this build.
	 * 
	 *  Network failures return `latest: None` rather than an error: the checker
	 *  runs on startup, and an offline machine must not surface a red banner for
	 *  what is only a missed HTTP call. The result is cached with the ordinary
	 *  resolver cache, so repeated checks are cheap.
	 */
	updateCheck: () => typedError<UpdateStatus, DevxError>(__TAURI_INVOKE("update_check")),
};

/** Events */
export const events = {
	installProgress: makeEvent<InstallProgress>("install-progress"),
};

/* Types */
/**  `From`, `To`, ... as Mailpit models them: a display name and address. */
export type Address = {
	/**  The `user@host` part. */
	address: string,
	/**  Display name, empty when the message has none. */
	name: string,
};

/**
 *  Identifying information about this DevX build.
 * 
 *  Surfaced in the UI footer and by `devx doctor`, and useful in bug reports.
 */
export type AppInfo = {
	/**  Product name. */
	name: string,
	/**  Semantic version of the DevX build. */
	version: string,
	/**  Rust target triple this binary was compiled for. */
	target: string,
	/**  Whether this is a debug build. */
	debug: boolean,
};

/**  Resolved locations DevX reads from and writes to. */
export type AppPaths = {
	/**  Root for user configuration. */
	config_dir: string,
	/**  Root for runtimes, service data, logs and caches. */
	data_dir: string,
};

/**  Archive format of a downloaded artifact. */
export type ArchiveKind = 
/**  A `.zip` archive. */
"zip" | 
/**  A gzip-compressed tarball. */
"tar_gz" | 
/**  A single executable, downloaded as-is. */
"executable";

/**  A downloadable artifact. */
export type Artifact = {
	/**  Direct download URL. */
	url: string,
	/**  File name to save it as. */
	file_name: string,
	/**
	 *  Size in bytes, when the upstream reports it.
	 * 
	 *  Exported to TypeScript as a plain `number`. Specta forbids `u64` by
	 *  default because JSON parsing truncates past 2^53; artifact sizes are
	 *  bounded by a few hundred megabytes, so the precision loss cannot occur.
	 */
	size_bytes: number | null,
	/**  Archive format. */
	archive: ArchiveKind,
	/**  How to verify the download. */
	checksum: Checksum,
};

/**  One attachment of a full message. */
export type Attachment = {
	/**  MIME part identifier within the message. */
	part_id: string,
	/**  File name Mailpit reports. */
	file_name: string,
	/**  MIME content type. */
	content_type: string,
	/**  Size in bytes, exported to TypeScript as a plain `number`. */
	size: number,
};

/**  The local CA's trust status, for the UI. */
export type CaStatus = {
	/**  Whether the CA exists on disk (signed certificates are possible). */
	exists: boolean,
	/**
	 *  Whether the machine trusts the CA (browsers accept its certificates).
	 *  `None` when the privileged helper is unavailable to check.
	 */
	trusted: boolean | null,
};

/**  A single diagnostic result. */
export type Check = {
	/**  Stable identifier, used by the UI to attach a repair action. */
	id: string,
	/**  Short human-readable name. */
	title: string,
	/**  Outcome. */
	status: CheckStatus,
	/**  What was actually observed. */
	detail: string,
	/**  How to fix it, when the status is not `Pass`. */
	remedy: string | null,
};

/**  Outcome of a single diagnostic check. */
export type CheckStatus = 
/**  Nothing to do. */
"pass" | 
/**  Works, but something will bite the user later. */
"warn" | 
/**  DevX cannot function until this is resolved. */
"fail";

/**
 *  How the SHA-256 of an artifact is obtained.
 * 
 *  Some upstreams publish the hash in their version index (PHP, GitHub release
 *  digests); others publish a separate sums file per release (Node). Deferring
 *  the second kind until download time avoids one extra request per version just
 *  to populate a list the user may never install from.
 */
export type Checksum = 
/**  Known now: lowercase hex SHA-256. */
{ kind: "sha256"; 
/**  Lowercase hex digest. */
hex: string } | 
/**  Published in a `sha256sum`-style file that lists `<hash>  <file name>`. */
{ kind: "sha256_file"; 
/**  URL of the sums file. */
url: string; 
/**  Entry to look for inside it. */
file_name: string };

/**  What a component is for, used for grouping in the UI. */
export type ComponentKind = 
/**  Language runtime such as PHP or Node. */
"runtime" | 
/**  HTTP server or reverse proxy. */
"web_server" | 
/**  Relational database. */
"database" | 
/**  Key-value cache. */
"cache" | 
/**  Mail catcher. */
"mail" | 
/**  Object storage. */
"storage" | 
/**  Search engine. */
"search" | 
/**  Developer tool such as Composer. */
"tool" | 
/**  Tunnelling client used for sharing sites. */
"tunnel";

/**
 *  What the UI needs to know about a component.
 * 
 *  Deliberately separate from [`Component`]: the frontend has no business
 *  knowing asset patterns, repository names or pinned URLs, and keeping the
 *  catalog schema out of the IPC contract means `#[serde(default)]` on the
 *  on-disk format does not leak into the generated TypeScript.
 */
export type ComponentSummary = {
	/**  Stable identifier. */
	id: string,
	/**  Display name. */
	name: string,
	/**  Grouping for the UI. */
	kind: ComponentKind,
	/**  One-line description. */
	summary: string,
	/**  Project homepage. */
	homepage: string,
	/**  Licence identifier. */
	license: string,
	/**  Whether several versions may coexist. */
	multi_version: boolean,
	/**  Caveat to show before installing, when there is one. */
	caveat: string | null,
	/**
	 *  Whether versions come from a fixed list rather than a live upstream.
	 * 
	 *  Pinned components cannot offer versions newer than the DevX catalog, so
	 *  the UI can explain why the list looks short.
	 */
	pinned: boolean,
};

/**  A version of a component that DevX can install. */
export type ComponentVersion = {
	/**  Component this version belongs to. */
	component_id: string,
	/**  Version string as published upstream, e.g. `8.4.25`. */
	version: string,
	/**  Release track. */
	channel: ReleaseChannel,
	/**  Release date as `YYYY-MM-DD`, when known. */
	released_at: string | null,
	/**  The artifact implementing this version. */
	artifact: Artifact,
};

/**
 *  Complete DevX configuration.
 * 
 *  Deliberately has no `#[serde(default)]`: every field is required on the wire
 *  so the generated TypeScript type has no optional properties. Robustness for
 *  partial or hand-edited files comes from [`merge_over_defaults`], which fills
 *  gaps before deserialization.
 */
export type Config = {
	/**  Version of this document's schema. */
	schema_version: number,
	/**  Application-wide preferences. */
	general: General,
	/**  Networking and local domain settings. */
	network: Network,
	/**  Component download and installation behaviour. */
	provisioning: Provisioning,
	/**  FastCGI worker counts per installed PHP version. */
	php_pools: PhpPools,
	/**  User-configured local sites. */
	sites: Site[],
};

/**  How to reach one database server. */
export type ConnectionParams = {
	/**  Which engine speaks on the other end. */
	engine: Engine,
	/**  Host, almost always `127.0.0.1` for supervised services. */
	host: string,
	/**  Port from the service's port allocation. */
	port: number,
	/**
	 *  Username; DevX services use `root` / `postgres` with no password by
	 *  default, so the field is optional.
	 */
	username: string | null,
	/**  Password, same story as the username. */
	password: string | null,
	/**  Optional database/schema to scope table listings to. */
	database: string | null,
};

/**  One column of a result set. */
export type DbColumn = {
	/**  Column name as the server reported it. */
	name: string,
};

/**  A tabular result: what the browser renders as a grid. */
export type DbResult = {
	/**  Column names, in order. */
	columns: DbColumn[],
	/**  Rows, each with one value per column. */
	rows: DbValue[][],
};

/**  A connectable database server, as the UI's connection picker sees it. */
export type DbServer = {
	/**  Engine behind the service. */
	engine: Engine,
	/**  Service id (`mariadb`, `postgresql`, `redis`). */
	service_id: string,
	/**  Host the service binds. */
	host: string,
	/**  Port from the service's allocation. */
	port: number,
	/**  Whether a TCP connection to the port succeeds right now. */
	reachable: boolean,
};

/**  A single cell of a result grid. */
export type DbValue = 
/**  SQL NULL — displayed distinctly from an empty string. */
"null" | 
/**
 *  An integer.
 * 
 *  Exported to TypeScript as a plain `number`. Specta forbids `i64` by
 *  default because JSON parsing truncates past 2^53; a display grid shows
 *  values as text, so the worst case is a rare cosmetic rounding on
 *  absurdly large values.
 */
({ int: number }) & { float?: never; other?: never; text?: never } | 
/**  A float. */
({ float: number | null }) & { int?: never; other?: never; text?: never } | 
/**  Bytes or text; the browser shows text. */
({ text: string }) & { float?: never; int?: never; other?: never } | 
/**  Anything else, rendered as the server's textual form. */
({ other: string }) & { float?: never; int?: never; text?: never };

/**
 *  A DevX error: a classification, a message, and optional operator guidance.
 * 
 *  Renamed for TypeScript so the generated binding does not shadow the global
 *  `Error`. `hint` is always serialized (rather than skipped when absent) to
 *  keep a single shape on the wire.
 */
export type DevxError = {
	/**  Machine-readable classification. */
	code: ErrorCode,
	/**  Human-readable description of what went wrong. */
	message: string,
	/**  Optional actionable next step shown to the user. */
	hint: string | null,
};

/**  How local domains are resolved. */
export type DnsMode = 
/**
 *  Prefer the bundled resolver with an NRPT rule, fall back to the hosts
 *  file when port 53 is unavailable.
 */
"auto" | 
/**  Always use the bundled resolver plus an NRPT rule. */
"resolver" | 
/**  Always write one hosts-file entry per site. No wildcard subdomains. */
"hosts_file";

/**  The bundled DNS resolver's status, for the UI. */
export type DnsStatus = {
	/**  Whether the resolver is running inside DevX right now. */
	running: boolean,
	/**  Port the resolver listens on, when running. */
	port: number | null,
	/**
	 *  Whether the NRPT rule routes `.test` queries to DevX. `None` when
	 *  the privileged helper is unavailable to check.
	 */
	nrpt_active: boolean | null,
	/**  The suffix the resolver answers for. */
	suffix: string,
};

/**  Full diagnostic report. */
export type DoctorReport = {
	/**  Worst status across all checks. */
	status: CheckStatus,
	/**  Individual results, in display order. */
	checks: Check[],
};

/**  Supported engines. */
export type Engine = 
/**  MariaDB or MySQL, both speak the MySQL protocol. */
"maria_db" | 
/**  PostgreSQL. */
"postgre_sql" | 
/**  Redis (and Redis-compatible servers). */
"redis";

/**
 *  Stable, machine-readable error classification.
 * 
 *  The string form is part of the IPC contract with the frontend; do not rename
 *  variants without updating the UI.
 */
export type ErrorCode = 
/**  Input failed validation before any side effect was attempted. */
"invalid_input" | 
/**  A required file, directory, component or record does not exist. */
"not_found" | 
/**  The requested change conflicts with existing state. */
"conflict" | 
/**  Filesystem-level failure. */
"io" | 
/**  Configuration could not be read, parsed or migrated. */
"config" | 
/**  Network failure while talking to an upstream service. */
"network" | 
/**  A downloaded artifact failed integrity verification. */
"integrity" | 
/**  Failure while starting, stopping or supervising a process. */
"process" | 
/**  The privileged helper is unavailable or refused the request. */
"privileged" | 
/**  Something failed that we could not classify. */
"internal";

/**  Application-wide preferences. */
export type General = {
	/**  UI colour scheme. */
	theme: Theme,
	/**  Launch DevX when the user signs in. */
	start_with_windows: boolean,
	/**  Closing the window hides it to the tray instead of exiting. */
	close_to_tray: boolean,
	/**  Start services that were running when DevX last exited. */
	restore_services_on_start: boolean,
};

/**
 *  Where an install currently is, mirrored from
 *  [`devx_provision::InstallStage`] into an IPC-friendly shape.
 */
export type InstallPhase = 
/**  Resolving a separately-published checksum. */
{ stage: "resolving_checksum" } | 
/**  Downloading, with byte counts. */
{ stage: "downloading"; 
/**  Bytes fetched so far. */
downloaded: number; 
/**  Total bytes, when the server reports a length. */
total: number | null } | 
/**  Verifying the SHA-256. */
{ stage: "verifying" } | 
/**  Extracting the archive. */
{ stage: "extracting" } | 
/**  Promoting the staged directory into place. */
{ stage: "finalising" } | 
/**  Complete. */
{ stage: "done" };

/**
 *  Progress of a component installation.
 * 
 *  One install emits a stream of these, keyed by `component_id` and `version`
 *  so the UI can route them to the right row when several run at once.
 */
export type InstallProgress = {
	/**  Component being installed. */
	component_id: string,
	/**  Version being installed. */
	version: string,
	/**  Current phase. */
	phase: InstallPhase,
};

/**  A version of a component that is installed on disk. */
export type InstalledVersion = {
	/**  Component identifier. */
	component_id: string,
	/**  Installed version string. */
	version: string,
	/**  Absolute install directory. */
	path: string,
};

/**  One captured log line, for the UI tail. */
export type LogEntry = {
	/**  Monotonic sequence number. */
	seq: number,
	/**  Which stream it came from. */
	stream: LogStream,
	/**  Line text. */
	text: string,
};

/**  Which standard stream a line came from. */
export type LogStream = 
/**  Standard output. */
"stdout" | 
/**  Standard error. */
"stderr";

/**  Status of the Mailpit service, as the Mail page needs it. */
export type MailStatus = {
	/**  Whether the `mailpit` service is currently running. */
	running: boolean,
	/**  Port the HTTP UI (and API) answers on; `null` while stopped. */
	port: number | null,
	/**  SMTP port apps should send mail to. */
	smtp_port: number,
	/**
	 *  Total and unread counts, when the API is reachable right now.
	 * 
	 *  Exported to TypeScript as plain `number`s (see the repo-wide `u64`
	 *  note); `null` while the API is unreachable.
	 */
	total: number | null,
	/**  Unread count, when the API is reachable right now. */
	unread: number | null,
};

/**  A full message (`GET /api/v1/message/{id}`): summary fields plus body. */
export type Message = {
	/**  Mailpit's short database ID. */
	id: string,
	/**  Sender. */
	from: Address,
	/**  Primary recipients. */
	to: Address[],
	/**  CC recipients. */
	cc: Address[],
	/**  BCC recipients. */
	bcc: Address[],
	/**  Subject line. */
	subject: string,
	/**  Message date, falling back to receive time (RFC 3339). */
	date: string,
	/**  Plain-text body, when the message has one. */
	text: string | null,
	/**  HTML body, when the message has one. */
	html: string | null,
	/**
	 *  Size of the raw message in bytes.
	 * 
	 *  Exported to TypeScript as a plain `number`; see the repo-wide note on
	 *  `u64` fields — display values never approach 2^53.
	 */
	size: number,
	/**  Tags Mailpit attached to the message. */
	tags: string[],
	/**  Attachments, metadata only (bytes stay in Mailpit). */
	attachments: Attachment[],
};

/**  One message in the inbox listing (`GET /api/v1/messages`). */
export type MessageSummary = {
	/**  Mailpit's short database ID; the key for every other call. */
	id: string,
	/**  Whether the message has been read (viewed) already. */
	read: boolean,
	/**  Sender. */
	from: Address,
	/**  Primary recipients. */
	to: Address[],
	/**  Subject line, possibly empty. */
	subject: string,
	/**  When the message was received (RFC 3339). */
	created: string,
	/**
	 *  Size of the raw message in bytes.
	 * 
	 *  Exported to TypeScript as a plain `number`; see the repo-wide note on
	 *  `u64` fields — display values never approach 2^53.
	 */
	size: number,
	/**  How many attachments the message carries. */
	attachments: number,
	/**  Up to 250 characters of plain-text preview. */
	snippet: string,
	/**  Tags Mailpit attached to the message. */
	tags: string[],
};

/**  Networking and local domain settings. */
export type Network = {
	/**
	 *  Suffix for local sites, without a leading dot. `test` is reserved by
	 *  RFC 6761 for exactly this purpose and never resolves publicly.
	 */
	domain_suffix: string,
	/**  Port the local web server listens on for HTTP. */
	http_port: number,
	/**  Port the local web server listens on for HTTPS. */
	https_port: number,
	/**  Port the bundled DNS resolver binds to. */
	dns_port: number,
	/**  Strategy used to resolve local domains. */
	dns_mode: DnsMode,
};

/**  A summary of one PHP FastCGI pool, including its live state. */
export type PhpPoolStatus = {
	/**  Pool identifier (`php-pool-8.4.25`). */
	id: string,
	/**  PHP version served by this pool. */
	version: string,
	/**  FastCGI workers configured for the pool. */
	workers: number,
	/**  Port the pool's FastCGI socket binds to. */
	port: number,
	/**  Current lifecycle state. */
	state: ServiceState,
};

/**
 *  Worker counts for PHP FastCGI pools, keyed by PHP version.
 * 
 *  A pool is created per installed PHP version; this map remembers the
 *  worker count each pool was started with so the Services page and the next
 *  start agree. A version missing from the map uses the default worker
 *  count, so uninstalling PHP or resetting settings needs no cleanup here.
 */
export type PhpPools = 
/**  Pool worker counts keyed by PHP version. */
{ [key in string]: number };

/**  How the privileged helper looks from this machine right now. */
export type PrivilegedStatus = {
	/**  Whether the helper's named pipe answered. */
	available: boolean,
	/**  Protocol version of a reachable helper, when it answered. */
	protocol_version: number | null,
};

/**  Component download and installation behaviour. */
export type Provisioning = {
	/**  Catalog describing components, versions and artifact hashes. */
	catalog_url: string,
	/**  Keep downloaded archives after a successful install. */
	keep_archives: boolean,
	/**  Maximum simultaneous downloads. */
	max_concurrent_downloads: number,
	/**  Refresh version metadata automatically on startup. */
	auto_refresh_catalog: boolean,
};

/**  Release track a version belongs to. */
export type ReleaseChannel = 
/**  Long-term support release, preferred default where upstream defines one. */
"lts" | 
/**  Current stable release. */
"stable" | 
/**  Pre-release, only offered when the catalog opts in. */
"prerelease";

/**  Where a supervised service is in its lifecycle. */
export type ServiceState = 
/**  Not running, and not trying to. */
"stopped" | 
/**  Spawned, waiting for its health check to pass. */
"starting" | 
/**  Running and healthy. */
"running" | 
/**  Asked to stop, waiting for the process to exit. */
"stopping" | 
/**  Exited unexpectedly, or failed to start. */
"failed";

/**  Status of a supervised service, for the UI. */
export type ServiceStatus = {
	/**  Service identifier. */
	id: string,
	/**  Current lifecycle state. */
	state: ServiceState,
};

/**
 *  One user-configured site.
 * 
 *  Stored in `config.toml` under `[[sites]]`; rendered into nginx server
 *  blocks by `devx-provision::sites` whenever the configuration changes.
 */
export type Site = {
	/**  Host name served, e.g. `myapp.test`. */
	hostname: string,
	/**  Absolute path of the folder nginx serves. */
	docroot: string,
	/**  PHP version whose pool serves the site, empty for a static site. */
	php_version: string,
	/**  Serve the site over HTTPS with the local CA's certificate. */
	https?: boolean,
};

/**  One site as the UI sees it, with the resolved FastCGI endpoint. */
export type SiteStatus = {
	/**  Host name served. */
	hostname: string,
	/**  Absolute docroot path. */
	docroot: string,
	/**  PHP version serving the site, empty for a static site. */
	php_version: string,
	/**  The `fastcgi_pass` endpoint, when the site runs PHP. */
	php_endpoint: string | null,
	/**  Whether the site is served over HTTPS with the local CA certificate. */
	https: boolean,
};

/**  UI colour scheme. */
export type Theme = 
/**  Follow the Windows setting. */
"system" | 
/**  Always light. */
"light" | 
/**  Always dark. */
"dark";

/**  Status of one site's public share, as the UI shows it. */
export type TunnelStatus = {
	/**  The shared site's local host name. */
	hostname: string,
	/**  Whether the cloudflared process is running. */
	running: boolean,
	/**
	 *  The public `https://…trycloudflare.com` URL, once assigned.
	 * 
	 *  Cloudflare announces it on stdout shortly after start, so this is
	 *  `null` for a few seconds after `tunnel_start`.
	 */
	url: string | null,
};

/**  Whether a newer DevX release is available upstream. */
export type UpdateStatus = {
	/**  Version of the running build. */
	current: string,
	/**  Newest release tag upstream, when one could be resolved. */
	latest: string | null,
	/**  Whether `latest` is newer than `current`. */
	update_available: boolean,
	/**  Release page for the new version, when known. */
	url: string | null,
};

/**  Result of listing versions, including whether the data was stale. */
export type VersionListing = {
	/**  Versions, newest first. */
	versions: ComponentVersion[],
	/**  Whether the underlying metadata came from a stale cache. */
	stale: boolean,
	/**  Versions that were skipped because no checksum is published for them. */
	unverifiable: string[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

