// Generated by tauri-specta from apps/desktop/src-tauri/src/ipc.rs.
// Do not edit by hand: run `cargo test -p devx-desktop` to verify.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Returns metadata about the running DevX build. */
	appInfo: () => typedError<AppInfo, DevxError>(__TAURI_INVOKE("app_info")),
	/**  Returns the resolved configuration and data directories. */
	pathsGet: () => typedError<AppPaths, DevxError>(__TAURI_INVOKE("paths_get")),
	/**  Returns the current configuration. */
	configGet: () => typedError<Config_Serialize, DevxError>(__TAURI_INVOKE("config_get")),
	/**
	 *  Validates and persists a replacement configuration.
	 * 
	 *  Returns the stored configuration, which may differ from the input where
	 *  DevX normalises values such as `schema_version`.
	 */
	configSet: (config: Config_Deserialize) => typedError<Config_Serialize, DevxError>(__TAURI_INVOKE("config_set", { config })),
	/**  Restores the default configuration. */
	configReset: () => typedError<Config_Serialize, DevxError>(__TAURI_INVOKE("config_reset")),
	/**
	 *  Exports the current configuration as TOML text.
	 * 
	 *  The text round-trips: `config_import` accepts it verbatim, and so does a
	 *  fresh DevX via the same parse-and-validate path a config file receives.
	 */
	configExport: () => typedError<string, DevxError>(__TAURI_INVOKE("config_export")),
	/**  Lists the saved profiles, alphabetically. */
	profileList: () => typedError<ProfileEntry[], DevxError>(__TAURI_INVOKE("profile_list")),
	/**
	 *  Lists every project folder: user-registered projects always appear (even
	 *  with nothing pointing into them yet), plus folders derived from configured
	 *  sites, workers and scheduled tasks.
	 */
	projectsList: () => typedError<ProjectSummary[], DevxError>(__TAURI_INVOKE("projects_list")),
	/**
	 *  Registers a folder as a managed project.
	 * 
	 *  The folder must already exist — the picker creates it on disk, not us —
	 *  and re-adding an existing path (case-insensitively) is the edit path for
	 *  the label, not an error.
	 */
	projectAdd: (path: string, label: string | null) => typedError<ProjectSummary[], DevxError>(__TAURI_INVOKE("project_add", { path, label })),
	/**
	 *  Removes a project from the registered list. The folder on disk is left
	 *  untouched — this only stops DevX from showing it as a managed project.
	 */
	projectRemove: (path: string) => typedError<ProjectSummary[], DevxError>(__TAURI_INVOKE("project_remove", { path })),
	/**
	 *  Updates a registered project's label and default runtime versions.
	 * 
	 *  A `None` argument leaves the field as-is; `Some("")` clears it back to
	 *  "follow the global default". Only registered projects can be updated.
	 */
	projectUpdate: (path: string, label: string | null, defaultPhp: string | null, defaultNode: string | null, defaultPython: string | null) => typedError<ProjectSummary[], DevxError>(__TAURI_INVOKE("project_update", { path, label, defaultPhp, defaultNode, defaultPython })),
	/**
	 *  Saves the current configuration as a named profile, overwriting an
	 *  existing profile of the same name on purpose.
	 */
	profileSave: (name: string) => typedError<ProfileEntry[], DevxError>(__TAURI_INVOKE("profile_save", { name })),
	/**
	 *  Applies a profile: validates it first, then replaces the running
	 *  configuration. Services pick the change up through their normal
	 *  re-plan paths, exactly as after an import.
	 */
	profileApply: (name: string) => typedError<Config_Serialize, DevxError>(__TAURI_INVOKE("profile_apply", { name })),
	/**  Deletes a saved profile. The running configuration is untouched. */
	profileDelete: (name: string) => typedError<ProfileEntry[], DevxError>(__TAURI_INVOKE("profile_delete", { name })),
	/**
	 *  Imports a configuration from TOML text, validating before it persists.
	 * 
	 *  Missing sections fall back to defaults, so a partial export still imports;
	 *  anything invalid is refused and leaves the running configuration alone.
	 */
	configImport: (body: string) => typedError<Config_Serialize, DevxError>(__TAURI_INVOKE("config_import", { body })),
	/**  Runs environment diagnostics against the live system. */
	doctorRun: () => typedError<DoctorReport, DevxError>(__TAURI_INVOKE("doctor_run")),
	/**
	 *  Applies the automatic repair for one doctor check.
	 * 
	 *  Only checks that expose a `fix` id can be repaired; the ids are the stable
	 *  `Check.id` values from the diagnostic report. Currently repairable:
	 * 
	 *  - `config` — backs the broken file up next to itself and regenerates
	 *    defaults, so the user keeps the broken file to inspect or recover.
	 */
	doctorFix: (checkId: string) => typedError<DoctorReport, DevxError>(__TAURI_INVOKE("doctor_fix", { checkId })),
	/**
	 *  Returns the newest service events from the persistent log, newest first.
	 * 
	 *  The log survives app restarts, so this answers "what happened while I
	 *  was away" — including failures the live badge already moved past.
	 */
	eventsRecent: (limit: number | null) => typedError<EventEntry[], DevxError>(__TAURI_INVOKE("events_recent", { limit })),
	/**
	 *  What §98's panel shows: the recorded transitions, newest first, each marked
	 *  read or unread, plus the unread count behind the bell's badge.
	 * 
	 *  Reading is free of side effects — opening the panel must not mark anything
	 *  read, or §98's "Mark all read" would have nothing left to do.
	 */
	notificationsList: (limit: number | null) => typedError<NotificationList, DevxError>(__TAURI_INVOKE("notifications_list", { limit })),
	/**
	 *  §98's "Mark all read": everything recorded so far is read.
	 * 
	 *  Failures are not read by this. §98 keeps an error visible until it is
	 *  acknowledged, so one that has not been cleared stays in the list and in the
	 *  badge — that is the point of the rule, not an oversight.
	 */
	notificationsMarkAllRead: (limit: number | null) => typedError<NotificationList, DevxError>(__TAURI_INVOKE("notifications_mark_all_read", { limit })),
	/**
	 *  §98's "Clear": everything recorded so far is acknowledged, so the panel
	 *  empties.
	 * 
	 *  Only the marker moves. `events.jsonl` is never edited, so the same
	 *  transitions stay on the Activity timeline (§42) and in the logs — clearing
	 *  notifications is not deleting history.
	 */
	notificationsClear: (limit: number | null) => typedError<NotificationList, DevxError>(__TAURI_INVOKE("notifications_clear", { limit })),
	/**
	 *  The disk use of DevX's managed directories, biggest last.
	 * 
	 *  Only the four directories users can meaningfully shrink are listed;
	 *  `certs` and `cache` are rounded off as noise.
	 */
	diskUsage: () => typedError<DirUsage[], DevxError>(__TAURI_INVOKE("disk_usage")),
	/**
	 *  The port map: every port DevX claims and who claims it.
	 * 
	 *  Covers the network ports from configuration (web, DNS), every supervised
	 *  service with a bound port, and every rendered FastCGI pool — so the user
	 *  can see, in one glance, which port belongs to what before starting
	 *  something new.
	 */
	portMap: () => typedError<PortEntry[], DevxError>(__TAURI_INVOKE("port_map")),
	/**
	 *  Every TCP port in the `LISTEN` state, with the process holding it (§110).
	 * 
	 *  This is the whole machine, not DevX's own reservations: `port_map` answers
	 *  "which ports does DevX claim", this answers "who is listening, right now".
	 *  The two are deliberately separate commands, so the UI cannot present one as
	 *  the other.
	 * 
	 *  Read-only and unprivileged, and it reports a failure rather than an empty
	 *  list, because "no port is listening" is a claim about the machine that a
	 *  failed read cannot support.
	 */
	listeningPorts: () => typedError<PortOwner[], DevxError>(__TAURI_INVOKE("listening_ports")),
	/**
	 *  Stops the process holding `port`, after the user confirmed it (§110).
	 * 
	 *  The guards, in order, and what each one is for:
	 * 
	 *  1. The guard below rules out three PIDs before anything else runs.
	 *  2. The listener table is read *again* here, and the PID has to still hold
	 *     that port. The PID the user clicked came from a list that is already
	 *     seconds old, and Windows reuses PIDs the moment a process exits, so
	 *     without this the command could end an unrelated process that inherited
	 *     the number. A stale row can then only fail the check.
	 *  3. The termination itself is the OS's decision. A process owned by SYSTEM or
	 *     by another account is refused with "Access is denied", and that refusal
	 *     is reported as-is: no retry, no elevation, no helper service. The user
	 *     gets the reason instead of a command that looks like it worked.
	 */
	stopProcessOnPort: (pid: number, port: number) => typedError<null, DevxError>(__TAURI_INVOKE("stop_process_on_port", { pid, port })),
	/**  Lists the components DevX can install. */
	catalogList: () => typedError<ComponentSummary[], DevxError>(__TAURI_INVOKE("catalog_list")),
	/**
	 *  Lists the installable versions of one component.
	 * 
	 *  Hits the component's upstream through a revalidating cache, so repeated calls
	 *  are cheap and a network failure returns the last known list marked stale
	 *  rather than an error.
	 */
	componentVersions: (componentId: string) => typedError<VersionListing, DevxError>(__TAURI_INVOKE("component_versions", { componentId })),
	/**
	 *  Installs a component version, emitting [`InstallProgress`] events.
	 * 
	 *  Returns the install directory on success. Progress is delivered through
	 *  events keyed by component and version so the UI can update the right row.
	 */
	componentInstall: (componentId: string, version: string) => typedError<string, DevxError>(__TAURI_INVOKE("component_install", { componentId, version })),
	/**
	 *  Cancels a running [`component_install`].
	 * 
	 *  Returns whether an install was actually running. The install aborts at the
	 *  next chunk boundary and cleans up: the partial download is kept so the next
	 *  attempt resumes from it, while the staging directory is removed.
	 */
	componentInstallCancel: (componentId: string, version: string) => typedError<boolean, DevxError>(__TAURI_INVOKE("component_install_cancel", { componentId, version })),
	/**  Removes an installed component version. */
	componentUninstall: (componentId: string, version: string) => typedError<null, DevxError>(__TAURI_INVOKE("component_uninstall", { componentId, version })),
	/**
	 *  Lists every installed component version found on disk.
	 * 
	 *  For supervisable services this also pre-renders the service's config
	 *  directory. Without that, `service-config/<id>` only came into existence at
	 *  first start, so a freshly installed service's "Open config folder" pointed
	 *  at a folder that did not exist yet. Rendering is idempotent and the plan is
	 *  rebuilt at start anyway, so pre-rendering here can never go stale in a way
	 *  that matters. Rendering failures are logged, not fatal: a broken template
	 *  would otherwise hide the whole install list, and the start path surfaces
	 *  the same error with its own context when it reaches the same code.
	 */
	installedVersions: () => typedError<InstalledVersion[], DevxError>(__TAURI_INVOKE("installed_versions")),
	/**  Lists the component ids that DevX can supervise as background services. */
	serviceComponentIds: () => typedError<string[], DevxError>(__TAURI_INVOKE("service_component_ids")),
	/**
	 *  Starts a supervised service backed by an installed component version.
	 * 
	 *  Resolves the service plan (config rendering, port allocation), runs any
	 *  pending one-time init steps, then registers and starts the supervisor.
	 *  Returns once the service is running or the start has failed.
	 */
	serviceStart: (componentId: string, version: string) => typedError<ServiceStatus, DevxError>(__TAURI_INVOKE("service_start", { componentId, version })),
	/**  Stops a running supervised service. */
	serviceStop: (id: string) => typedError<ServiceStatus, DevxError>(__TAURI_INVOKE("service_stop", { id })),
	/**  Starts every service that is not running; see [`BatchStartOutcome`]. */
	servicesStartAll: () => typedError<BatchStartOutcome[], DevxError>(__TAURI_INVOKE("services_start_all")),
	/**
	 *  Stops every active supervised service, concurrently and non-fatal per
	 *  service, exactly as [`services_start_all`] starts them.
	 */
	servicesStopAll: () => typedError<BatchStartOutcome[], DevxError>(__TAURI_INVOKE("services_stop_all")),
	/**  Returns the status of a supervised service. */
	serviceStatus: (id: string) => typedError<ServiceStatus, DevxError>(__TAURI_INVOKE("service_status", { id })),
	/**  Returns log lines for a service newer than `after` (0 for all retained). */
	serviceLogs: (id: string, after: number) => typedError<LogEntry[], DevxError>(__TAURI_INVOKE("service_logs", { id, after })),
	/**
	 *  Samples the CPU and memory use of every supervised service.
	 * 
	 *  CPU percent is relative to the previous sample this process took, so the
	 *  first call after launch reports 0. Stopped services report zero usage but
	 *  are still listed, letting the dashboard zip this against the service list.
	 */
	serviceMetrics: () => typedError<ServiceMetrics[], DevxError>(__TAURI_INVOKE("service_metrics")),
	/**
	 *  Sets or clears a custom port for a supervised service component or PHP pool.
	 * 
	 *  If port is `Some(p)`, sets the custom port (p must be > 0). If `None`, clears the custom port.
	 *  Re-renders configuration, restarts active services/pools, and re-syncs site blocks.
	 */
	serviceSetPort: (componentId: string, port: number | null) => typedError<{ [key in string]: number }, DevxError>(__TAURI_INVOKE("service_set_port", { componentId, port })),
	/**  Returns the configured custom service ports map. */
	serviceGetPorts: () => typedError<{ [key in string]: number }, DevxError>(__TAURI_INVOKE("service_get_ports")),
	/**  Lists every log file DevX has written, newest first. */
	logsList: () => typedError<LogFileInfo[], DevxError>(__TAURI_INVOKE("logs_list")),
	/**
	 *  Reads the last `tail` lines of one DevX log file.
	 * 
	 *  The file name is validated against the logs directory so the viewer can
	 *  never be coaxed into reading anything else on the machine.
	 */
	logsRead: (fileName: string, tail: number) => typedError<LogFileContent, DevxError>(__TAURI_INVOKE("logs_read", { fileName, tail })),
	/**
	 *  Lists the PHP FastCGI pools DevX can supervise: one per installed PHP.
	 * 
	 *  Pools are planned on the fly rather than persisted, so the list always
	 *  matches what is on disk. Workers reflect the stored setting when the pool
	 *  has one, and the default otherwise.
	 * 
	 *  Each listed pool's config files are (re-)rendered here. Without this the
	 *  `service-config/<pool>` directory only came into existence at first start,
	 *  so a freshly installed version's "Open config folder" pointed at a folder
	 *  that did not exist yet. The pool's settings (extensions, Xdebug, limits)
	 *  are still rendered again at start, so rendering here can never go stale in
	 *  a way that matters.
	 */
	phpPoolList: () => typedError<PhpPoolStatus[], DevxError>(__TAURI_INVOKE("php_pool_list")),
	/**  Starts (or reports) the FastCGI pool for one installed PHP version. */
	phpPoolStart: (version: string, workers: number) => typedError<PhpPoolStatus, DevxError>(__TAURI_INVOKE("php_pool_start", { version, workers })),
	/**  Stops the FastCGI pool of one PHP version. */
	phpPoolStop: (version: string) => typedError<PhpPoolStatus, DevxError>(__TAURI_INVOKE("php_pool_stop", { version })),
	/**  Returns the status of one PHP pool, stopped when it has never started. */
	phpPoolStatus: (version: string) => typedError<PhpPoolStatus, DevxError>(__TAURI_INVOKE("php_pool_status", { version })),
	/**
	 *  Returns log lines for a pool newer than `after` (0 for all retained).
	 * 
	 *  Pools reuse the service log machinery; this alias keeps the UI from
	 *  reaching into service ids by hand.
	 */
	phpPoolLogs: (version: string, after: number) => typedError<LogEntry[], DevxError>(__TAURI_INVOKE("php_pool_logs", { version, after })),
	/**  Lists the extensions of one installed PHP version and which are enabled. */
	phpExtList: (version: string) => typedError<PhpExtensionInfo, DevxError>(__TAURI_INVOKE("php_ext_list", { version })),
	/**
	 *  Enables or disables one extension of a PHP version.
	 * 
	 *  The setting is persisted first; a running pool is then restarted with a
	 *  re-rendered `php.ini`, so the change applies immediately. A failed restart
	 *  does not roll back the setting — the next manual start picks it up.
	 */
	phpExtSet: (version: string, extension: string, enabled: boolean) => typedError<PhpExtensionInfo, DevxError>(__TAURI_INVOKE("php_ext_set", { version, extension, enabled })),
	/**  Reads the Xdebug configuration of one installed PHP version. */
	phpXdebugGet: (version: string) => typedError<PhpXdebugInfo, DevxError>(__TAURI_INVOKE("php_xdebug_get", { version })),
	/**
	 *  Enables, disables or reconfigures Xdebug for one PHP version.
	 * 
	 *  `enabled = false` clears the stored configuration entirely; `enabled = true`
	 *  with an empty `mode` means Xdebug's default debugger profile. A running
	 *  pool restarts with the re-rendered ini, exactly like an extension toggle.
	 */
	phpXdebugSet: (version: string, enabled: boolean, mode: string, clientPort: number) => typedError<PhpXdebugInfo, DevxError>(__TAURI_INVOKE("php_xdebug_set", { version, enabled, mode, clientPort })),
	/**
	 *  The resource limits for `version`, or the built-in defaults when the
	 *  version has no stored override.
	 */
	phpLimitsGet: (version: string) => typedError<LimitConfig, DevxError>(__TAURI_INVOKE("php_limits_get", { version })),
	/**
	 *  Sets the resource limits for `version`, restarting a running pool so the
	 *  re-rendered ini takes effect immediately.
	 */
	phpLimitsSet: (version: string, limits: LimitConfig) => typedError<LimitConfig, DevxError>(__TAURI_INVOKE("php_limits_set", { version, limits })),
	/**  Lists the configured sites with their resolved PHP endpoints. */
	siteList: () => typedError<SiteStatus[], DevxError>(__TAURI_INVOKE("site_list")),
	/**
	 *  Checks one site over HTTP(S) against its owning server.
	 * 
	 *  Resolves the host through the system resolver first (the bundled DNS or
	 *  the hosts file), then issues a real request so the check covers the whole
	 *  chain — DNS, TLS, server block, and PHP when the docroot runs it.
	 */
	sitePing: (hostname: string) => typedError<SitePing, DevxError>(__TAURI_INVOKE("site_ping", { hostname })),
	/**
	 *  The recent requests one site served, parsed from its access log.
	 * 
	 *  Understands the two formats DevX writes: nginx's combined format and
	 *  Caddy's JSON access log. Lines that match neither are skipped, so a
	 *  partially written last line never breaks the read. Newest entries first.
	 */
	siteRequests: (hostname: string, limit: number) => typedError<SiteRequestEntry[], DevxError>(__TAURI_INVOKE("site_requests", { hostname, limit })),
	/**  Adds (or replaces) a site — thin adapter over SiteOrchestrator. */
	siteAdd: (hostname: string, docroot: string, phpVersion: string, https: boolean, webServer: 
/**
 *  nginx — the default, and the only server with a rendered sites include
 *  before this field existed.
 */
"Nginx" | 
/**  Apache — classic web server with .htaccess support. */
"Apache" | 
/**  Caddy — minimal config, HTTP/2 and HTTP/3 out of the box. */
"Caddy" | 
/**  FrankenPHP — serves PHP directly, no FastCGI pool needed. */
"FrankenPhp" | null) => typedError<SiteStatus[], DevxError>(__TAURI_INVOKE("site_add", { hostname, docroot, phpVersion, https, webServer })),
	/**  Removes a site — thin adapter over SiteOrchestrator. */
	siteRemove: (hostname: string) => typedError<SiteStatus[], DevxError>(__TAURI_INVOKE("site_remove", { hostname })),
	/**  Sets one environment variable — thin adapter. */
	siteEnvSet: (hostname: string, key: string, value: string) => typedError<SiteStatus[], DevxError>(__TAURI_INVOKE("site_env_set", { hostname, key, value })),
	/**  Removes one environment variable — thin adapter. */
	siteEnvDelete: (hostname: string, key: string) => typedError<SiteStatus[], DevxError>(__TAURI_INVOKE("site_env_delete", { hostname, key })),
	/**  Reports the local CA's status: present on disk and machine-trusted. */
	caStatus: () => typedError<CaStatus, DevxError>(__TAURI_INVOKE("ca_status")),
	/**
	 *  Creates the local CA (if missing) and installs it into the machine trust
	 *  store through the privileged helper.
	 */
	caInstall: () => typedError<CaStatus, DevxError>(__TAURI_INVOKE("ca_install")),
	/**
	 *  Removes the DevX CA from the machine trust store (the on-disk CA and any
	 *  issued site certificates are left in place for a later reinstall).
	 */
	caRemove: () => typedError<CaStatus, DevxError>(__TAURI_INVOKE("ca_remove")),
	/**  Reports the bundled resolver's status and whether the NRPT rule is active. */
	dnsStatus: () => typedError<DnsStatus, DevxError>(__TAURI_INVOKE("dns_status")),
	/**
	 *  Starts the bundled DNS resolver and (through the helper) points the NRPT
	 *  rule at it. Idempotent: starting twice keeps the running instance.
	 */
	dnsStart: () => typedError<DnsStatus, DevxError>(__TAURI_INVOKE("dns_start")),
	/**
	 *  Re-installs the NRPT rule for the running resolver, prompting for
	 *  helper elevation when needed.
	 * 
	 *  The one-click remedy for "resolver running but names not resolving":
	 *  it starts the resolver when stopped, then makes sure the helper is up
	 *  (one UAC prompt the first time) and points the rule at the resolver's
	 *  actual port.
	 */
	dnsRepair: () => typedError<DnsStatus, DevxError>(__TAURI_INVOKE("dns_repair")),
	/**  Stops the bundled resolver and removes the NRPT rule. */
	dnsStop: () => typedError<DnsStatus, DevxError>(__TAURI_INVOKE("dns_stop")),
	/**
	 *  Lists the database servers DevX supervises and their reachability.
	 * 
	 *  Ports come from each service's rendered state where available, falling
	 *  back to the definition's default port, so this works before first start
	 *  (unreachable) and after restarts (reassigned ports picked up live).
	 */
	dbListServers: () => typedError<DbServer[], DevxError>(__TAURI_INVOKE("db_list_servers")),
	/**  Runs one read-only statement against `params` and renders a grid. */
	dbQuery: (params: ConnectionParams, statement: string) => typedError<DbResult, DevxError>(__TAURI_INVOKE("db_query", { params, statement })),
	/**  Lists the databases (schemas) visible on `params`. */
	dbListDatabases: (params: ConnectionParams) => typedError<DbResult, DevxError>(__TAURI_INVOKE("db_list_databases", { params })),
	/**  Lists the tables in `params.database`. */
	dbListTables: (params: ConnectionParams) => typedError<DbResult, DevxError>(__TAURI_INVOKE("db_list_tables", { params })),
	/**
	 *  Imports a plain SQL dump file into the running service.
	 * 
	 *  The file is replayed through the engine's own client, exactly like a
	 *  backup restore; Redis has no SQL import path. The service must be
	 *  running and the path must point to an existing `.sql` file.
	 */
	dbImportSql: (serviceId: string, filePath: string) => typedError<null, DevxError>(__TAURI_INVOKE("db_import_sql", { serviceId, filePath })),
	/**
	 *  Runs one read-only statement and writes the result grid to a CSV file.
	 * 
	 *  The first line is the header row; NULL renders as an empty field, the
	 *  same convention the browser grid uses. Returns the exported row count.
	 */
	dbExportCsv: (params: ConnectionParams, statement: string, filePath: string) => typedError<number, DevxError>(__TAURI_INVOKE("db_export_csv", { params, statement, filePath })),
	/**  Lists the backups of one database service, newest first. */
	backupList: (serviceId: string) => typedError<BackupEntry[], DevxError>(__TAURI_INVOKE("backup_list", { serviceId })),
	/**
	 *  Creates a backup of one database service and prunes old ones.
	 * 
	 *  MariaDB and PostgreSQL are dumped through their own tools into plain SQL;
	 *  Redis is snapshotted with a blocking `SAVE` and the RDB file copied. The
	 *  service must be running: the tools connect over TCP like any client.
	 */
	backupCreate: (serviceId: string) => typedError<BackupEntry, DevxError>(__TAURI_INVOKE("backup_create", { serviceId })),
	/**
	 *  Restores a database service from one of its backups.
	 * 
	 *  SQL dumps are replayed through the engine's client against the running
	 *  server; a Redis snapshot is copied back into the service data directory,
	 *  which requires the server to be stopped first.
	 */
	backupRestore: (serviceId: string, fileName: string) => typedError<null, DevxError>(__TAURI_INVOKE("backup_restore", { serviceId, fileName })),
	/**  Deletes one backup of a database service. */
	backupDelete: (serviceId: string, fileName: string) => typedError<null, DevxError>(__TAURI_INVOKE("backup_delete", { serviceId, fileName })),
	/**  Reports whether Mailpit is running and how full its inbox is. */
	mailStatus: () => typedError<MailStatus, DevxError>(__TAURI_INVOKE("mail_status")),
	/**  Lists the newest messages in Mailpit's inbox. */
	mailList: (limit: number) => typedError<MessageSummary[], DevxError>(__TAURI_INVOKE("mail_list", { limit })),
	/**  Fetches one full message by ID. Mailpit marks it read on fetch. */
	mailMessage: (id: string) => typedError<Message, DevxError>(__TAURI_INVOKE("mail_message", { id })),
	/**  Deletes the given messages, or every message when `ids` is empty. */
	mailDelete: (ids: string[]) => typedError<null, DevxError>(__TAURI_INVOKE("mail_delete", { ids })),
	/**
	 *  Marks every message in the inbox read.
	 * 
	 *  Mailpit's API only takes explicit ids, so this lists the inbox and marks
	 *  everything it returns — the same call the list view uses, so nothing is
	 *  read that the UI has not shown.
	 */
	mailMarkAllRead: () => typedError<null, DevxError>(__TAURI_INVOKE("mail_mark_all_read")),
	/**
	 *  Sends one clearly-labelled test email through Mailpit's own SMTP port.
	 * 
	 *  This is the round-trip check: the message enters via SMTP exactly as an
	 *  application's mail would, and appears in the inbox a second later. The
	 *  SMTP conversation is raw and unauthenticated because Mailpit's local
	 *  listener accepts everything.
	 */
	mailSendTest: () => typedError<null, DevxError>(__TAURI_INVOKE("mail_send_test")),
	/**
	 *  Shares `hostname` publicly through a Cloudflare quick tunnel.
	 * 
	 *  The tunnel targets the owning server's loopback and HTTP port (live
	 *  allocation or configured default), so the public URL reaches the same
	 *  site block the local `.test` host name does — no front door involved.
	 */
	tunnelStart: (hostname: string) => typedError<TunnelStatus, DevxError>(__TAURI_INVOKE("tunnel_start", { hostname })),
	/**  Stops the share for `hostname`, if one is running. */
	tunnelStop: (hostname: string) => typedError<TunnelStatus, DevxError>(__TAURI_INVOKE("tunnel_stop", { hostname })),
	/**
	 *  Reports the share status for `hostname`, parsing the tunnel URL from the
	 *  process's captured log output.
	 */
	tunnelStatus: (hostname: string) => typedError<TunnelStatus, DevxError>(__TAURI_INVOKE("tunnel_status", { hostname })),
	/**  Lists every configured worker with its live instance states. */
	workerList: () => typedError<WorkerStatus[], DevxError>(__TAURI_INVOKE("worker_list")),
	/**  Adds (or replaces) a configured worker. */
	workerAdd: (name: string, program: string | null, phpVersion: string | null, args: string[], workingDir: string, instances: number) => typedError<WorkerStatus[], DevxError>(__TAURI_INVOKE("worker_add", { name, program, phpVersion, args, workingDir, instances })),
	/**  Removes a worker, stopping any running instances first. */
	workerRemove: (name: string) => typedError<WorkerStatus[], DevxError>(__TAURI_INVOKE("worker_remove", { name })),
	/**  Starts every instance of a worker. Idempotent for running instances. */
	workerStart: (name: string) => typedError<WorkerStatus[], DevxError>(__TAURI_INVOKE("worker_start", { name })),
	/**  Stops every instance of a worker. */
	workerStop: (name: string) => typedError<WorkerStatus[], DevxError>(__TAURI_INVOKE("worker_stop", { name })),
	/**
	 *  Probes the privileged helper so the UI can show whether elevated
	 *  operations (hosts entries today, HTTPS and NRPT later) are possible.
	 * 
	 *  Deliberately cheap: an open-and-close of the pipe, no handshake round
	 *  trip, so it can be polled without cost.
	 */
	privilegedStatus: () => typedError<PrivilegedStatus, DevxError>(__TAURI_INVOKE("privileged_status")),
	/**
	 *  Reveals a DevX directory in File Explorer.
	 * 
	 *  Restricted to the managed directories (and anything beneath them, such as a
	 *  single service's config folder) so the command cannot be used to open
	 *  arbitrary paths from the webview.
	 * 
	 *  The directory is created first when missing: several of DevX's folders (a
	 *  service's `service-config/<id>`, for instance) only come into existence
	 *  after the service has run once, and a button that reports failure for a
	 *  folder DevX simply has not written yet reads as broken to the user.
	 */
	revealManagedDir: (path: string) => typedError<null, DevxError>(__TAURI_INVOKE("reveal_managed_dir", { path })),
	/**
	 *  Applies `general.start_with_windows` to the OS autostart entry.
	 * 
	 *  The registry key is the operating system's state, not DevX's, so it is
	 *  synced here when the user flips the toggle (and once at startup) rather
	 *  than being derived implicitly. Returns the resulting enabled state.
	 */
	settingsSyncAutostart: () => typedError<boolean, DevxError>(__TAURI_INVOKE("settings_sync_autostart")),
	/**
	 *  Checks the newest published DevX release and compares it to this build.
	 * 
	 *  Network failures return `latest: None` rather than an error: the checker
	 *  runs on startup, and an offline machine must not surface a red banner for
	 *  what is only a missed HTTP call. The result is cached with the ordinary
	 *  resolver cache, so repeated checks are cheap.
	 */
	updateCheck: () => typedError<UpdateStatus, DevxError>(__TAURI_INVOKE("update_check")),
	/**
	 *  Runs one command through `cmd /c` in `cwd`, streaming its output.
	 * 
	 *  Streams `TerminalOutput` events as lines arrive and resolves once the
	 *  process exits. This is a command runner, not a pty: interactive prompts
	 *  are not supported, which keeps the surface honest and typed. The child
	 *  gets the DevX runtimes on its `PATH` plus the usual working directory.
	 */
	terminalRun: (cwd: string, command: string) => typedError<TerminalExit, DevxError>(__TAURI_INVOKE("terminal_run", { cwd, command })),
	/**
	 *  The `PATH` string the terminal runs with: DevX runtimes first, then the
	 *  system's own `PATH` untouched.
	 */
	terminalPath: () => typedError<string, DevxError>(__TAURI_INVOKE("terminal_path")),
	/**
	 *  Pins a component version for the terminal by writing PATH shims.
	 * 
	 *  Mirrors `devx use <component> <version>` so the UI and the CLI share one
	 *  implementation (see `devx_provision::use_shim`).
	 */
	terminalUseVersion: (componentId: string, version: string) => typedError<null, DevxError>(__TAURI_INVOKE("terminal_use_version", { componentId, version })),
	/**  Clears any shims pinned for a component (the UI's unpin action). */
	terminalUnsetVersion: (componentId: string) => typedError<null, DevxError>(__TAURI_INVOKE("terminal_unset_version", { componentId })),
	/**
	 *  Lists the site templates DevX can scaffold.
	 * 
	 *  Templates follow the catalog's integrity policy: anything needing a
	 *  download without an obtainable checksum (WordPress publishes none for its
	 *  zip; Laravel scaffolds through composer) is not offered as a download —
	 *  the template only carries the suggested terminal command.
	 */
	templateList: () => typedError<TemplateInfo[], DevxError>(__TAURI_INVOKE("template_list")),
	/**
	 *  Scaffolds `template_id` into `docroot` and creates the site.
	 * 
	 *  Local templates write their files into the (created) docroot and never
	 *  overwrite existing content; download-based templates only create the
	 *  folder and return their suggested command, to be run in the Terminal.
	 *  The `git` template clones `git_url` with the system git before the site
	 *  is registered, so the docroot already holds real content.
	 */
	templateCreate: (templateId: string, hostname: string, docroot: string, phpVersion: string, https: boolean, gitUrl: string | null) => typedError<TemplateCreateResult, DevxError>(__TAURI_INVOKE("template_create", { templateId, hostname, docroot, phpVersion, https, gitUrl })),
	/**  Adds an alias — thin adapter. */
	siteAliasAdd: (hostname: string, alias: string) => typedError<SiteStatus[], DevxError>(__TAURI_INVOKE("site_alias_add", { hostname, alias })),
	/**  Sets basic-auth — thin adapter (hashing stays here, storage in orchestrator). */
	siteAuthSet: (hostname: string, username: string | null, password: string | null) => typedError<SiteStatus[], DevxError>(__TAURI_INVOKE("site_auth_set", { hostname, username, password })),
	/**  Removes an alias — thin adapter. */
	siteAliasDelete: (hostname: string, alias: string) => typedError<SiteStatus[], DevxError>(__TAURI_INVOKE("site_alias_delete", { hostname, alias })),
	/**  Lists the configured scheduled tasks with their Windows registration. */
	cronList: () => typedError<CronStatus[], DevxError>(__TAURI_INVOKE("cron_list")),
	/**
	 *  Creates or updates a scheduled task: persist the definition, then
	 *  reconcile the Windows task with it.
	 */
	cronSet: (name: string, program: string | null, phpVersion: string | null, args: string[], workingDir: string, everyMinutes: number) => typedError<CronStatus[], DevxError>(__TAURI_INVOKE("cron_set", { name, program, phpVersion, args, workingDir, everyMinutes })),
	/**  Deletes a scheduled task from the config and from Windows. */
	cronDelete: (name: string) => typedError<CronStatus[], DevxError>(__TAURI_INVOKE("cron_delete", { name })),
	/**
	 *  Lists the hosts entries DevX manages.
	 * 
	 *  Only marked entries: the file's other lines belong to the user and to the
	 *  system, and this command does not report them at all.
	 * 
	 *  # Errors
	 * 
	 *  Fails with [`devx_core::ErrorCode::Privileged`] when the helper is not
	 *  running. Elevation is deliberately not attempted from here.
	 */
	hostsList: () => typedError<HostsEntry[], DevxError>(__TAURI_INVOKE("hosts_list")),
	/**
	 *  Adds one DevX-managed hosts entry, or updates the existing one for that
	 *  host name.
	 * 
	 *  Returns the list as it stands after the change, so the caller never renders
	 *  a list it did not just read.
	 * 
	 *  # Errors
	 * 
	 *  Propagates validation failures (before anything is elevated), the
	 *  elevation failure when the helper cannot be started, and the helper's own
	 *  refusal — a host name already mapped by a line outside DevX's control is a
	 *  conflict, not something to overwrite.
	 */
	hostsAdd: (hostname: string, ip: string) => typedError<HostsEntry[], DevxError>(__TAURI_INVOKE("hosts_add", { hostname, ip })),
	/**
	 *  Removes the DevX-managed hosts entry for `hostname`.
	 * 
	 *  Returns the list as it stands after the change. Removing a name DevX does
	 *  not manage is not an error: there is nothing of DevX's to remove.
	 * 
	 *  # Errors
	 * 
	 *  Propagates validation failures, the elevation failure when the helper
	 *  cannot be started, and the helper's own refusal.
	 */
	hostsRemove: (hostname: string) => typedError<HostsEntry[], DevxError>(__TAURI_INVOKE("hosts_remove", { hostname })),
	/**
	 *  Drops the machine's DNS client resolver cache.
	 * 
	 *  Separate from the mutations on purpose: a name that resolved once keeps
	 *  resolving from the cache after the hosts file changed, and sometimes the
	 *  cache is the only thing that needs clearing.
	 * 
	 *  # Errors
	 * 
	 *  Propagates the elevation failure when the helper cannot be started, and the
	 *  helper's refusal when `ipconfig /flushdns` itself fails.
	 */
	hostsFlushDns: () => typedError<null, DevxError>(__TAURI_INVOKE("hosts_flush_dns")),
	/**
	 *  Rewrites every site hostname and alias with its owning server's loopback.
	 * 
	 *  The one-click repair for entries left stale by older DevX (a name pointing
	 *  at a previous address while its server moved on): entries for names no
	 *  site owns are left alone, so hand-added custom lines are never touched.
	 */
	hostsResync: () => typedError<HostsResyncResult, DevxError>(__TAURI_INVOKE("hosts_resync")),
	/**  Shows the main window, focusing it. */
	trayShowMain: () => typedError<null, DevxError>(__TAURI_INVOKE("tray_show_main")),
	/**
	 *  Quits the app, stopping every supervised service first (via the normal
	 *  exit path, which the tray used before the popup existed).
	 */
	trayQuit: () => typedError<null, DevxError>(__TAURI_INVOKE("tray_quit")),
};

/** Events */
export const events = {
	installProgress: makeEvent<InstallProgress>("install-progress"),
	serviceEventUpdate: makeEvent<ServiceEventUpdate>("service-event-update"),
	terminalOutput: makeEvent<TerminalOutput>("terminal-output"),
};

/* Types */
/**  `From`, `To`, ... as Mailpit models them: a display name and address. */
export type Address = {
	/**  The `user@host` part. */
	address: string,
	/**  Display name, empty when the message has none. */
	name: string,
};

/**
 *  Identifying information about this DevX build.
 * 
 *  Surfaced in the UI footer and by `devx doctor`, and useful in bug reports.
 */
export type AppInfo = {
	/**  Product name. */
	name: string,
	/**  Semantic version of the DevX build. */
	version: string,
	/**  Rust target triple this binary was compiled for. */
	target: string,
	/**  Whether this is a debug build. */
	debug: boolean,
};

/**  Resolved locations DevX reads from and writes to. */
export type AppPaths = {
	/**  Root for user configuration. */
	config_dir: string,
	/**  Root for runtimes, service data, logs and caches. */
	data_dir: string,
};

/**  Archive format of a downloaded artifact. */
export type ArchiveKind = 
/**  A `.zip` archive. */
"zip" | 
/**  A gzip-compressed tarball. */
"tar_gz" | 
/**  A single executable, downloaded as-is. */
"executable";

/**  A downloadable artifact. */
export type Artifact = {
	/**  Direct download URL. */
	url: string,
	/**  File name to save it as. */
	file_name: string,
	/**
	 *  Size in bytes, when the upstream reports it.
	 * 
	 *  Exported to TypeScript as a plain `number`. Specta forbids `u64` by
	 *  default because JSON parsing truncates past 2^53; artifact sizes are
	 *  bounded by a few hundred megabytes, so the precision loss cannot occur.
	 */
	size_bytes: number | null,
	/**  Archive format. */
	archive: ArchiveKind,
	/**  How to verify the download. */
	checksum: Checksum,
};

/**  One attachment of a full message. */
export type Attachment = {
	/**  MIME part identifier within the message. */
	part_id: string,
	/**  File name Mailpit reports. */
	file_name: string,
	/**  MIME content type. */
	content_type: string,
	/**  Size in bytes, exported to TypeScript as a plain `number`. */
	size: number,
};

/**  One database backup file, for the UI. */
export type BackupEntry = {
	/**  Service the backup belongs to (`mariadb`, `postgresql`, `redis`). */
	service_id: string,
	/**  File name inside the service's backups directory. */
	file_name: string,
	/**  Size on disk, in bytes. */
	size_bytes: number,
	/**  Creation time as Unix seconds. */
	created_unix: number,
};

/**
 *  Starts every registered service that is not already running.
 * 
 *  Starts run concurrently; each failure is collected rather than aborting
 *  the rest, so one broken service never blocks bringing up the others.
 *  The result pairs each id with its outcome, keeping partial-success
 *  honest in the UI.
 */
export type BatchStartOutcome = {
	/**  Service identifier. */
	id: string,
	/**  `None` on success; the error message when that one failed. */
	error: string | null,
};

/**  The local CA's trust status, for the UI. */
export type CaStatus = {
	/**  Whether the CA exists on disk (signed certificates are possible). */
	exists: boolean,
	/**
	 *  Whether the machine trusts the CA (browsers accept its certificates).
	 *  `None` when the privileged helper is unavailable to check.
	 */
	trusted: boolean | null,
};

/**  A single diagnostic result. */
export type Check = {
	/**  Stable identifier, used by the UI to attach a repair action. */
	id: string,
	/**  Short human-readable name. */
	title: string,
	/**  Outcome. */
	status: CheckStatus,
	/**  What was actually observed. */
	detail: string,
	/**  How to fix it, when the status is not `Pass`. */
	remedy: string | null,
	/**
	 *  Identifier of an automatic repair the app can perform, when one
	 *  exists. The UI renders a fix action for checks that carry it, and
	 *  `doctor_fix` accepts exactly these ids.
	 */
	fix: string | null,
};

/**  Outcome of a single diagnostic check. */
export type CheckStatus = 
/**  Nothing to do. */
"pass" | 
/**  Works, but something will bite the user later. */
"warn" | 
/**  DevX cannot function until this is resolved. */
"fail";

/**
 *  How the SHA-256 of an artifact is obtained.
 * 
 *  Some upstreams publish the hash in their version index (PHP, GitHub release
 *  digests); others publish a separate sums file per release (Node). Deferring
 *  the second kind until download time avoids one extra request per version just
 *  to populate a list the user may never install from.
 */
export type Checksum = 
/**  Known now: lowercase hex SHA-256. */
{ kind: "sha256"; 
/**  Lowercase hex digest. */
hex: string } | 
/**  Published in a `sha256sum`-style file that lists `<hash>  <file name>`. */
{ kind: "sha256_file"; 
/**  URL of the sums file. */
url: string; 
/**  Entry to look for inside it. */
file_name: string };

/**  What a component is for, used for grouping in the UI. */
export type ComponentKind = 
/**  Language runtime such as PHP or Node. */
"runtime" | 
/**  HTTP server or reverse proxy. */
"web_server" | 
/**  Relational database. */
"database" | 
/**  Key-value cache. */
"cache" | 
/**  Message queue server such as NATS. */
"message_queue" | 
/**  Mail catcher. */
"mail" | 
/**  Object storage. */
"storage" | 
/**  Search engine. */
"search" | 
/**  Developer tool such as Composer. */
"tool" | 
/**  Tunnelling client used for sharing sites. */
"tunnel";

/**
 *  What the UI needs to know about a component.
 * 
 *  Deliberately separate from [`Component`]: the frontend has no business
 *  knowing asset patterns, repository names or pinned URLs, and keeping the
 *  catalog schema out of the IPC contract means `#[serde(default)]` on the
 *  on-disk format does not leak into the generated TypeScript.
 */
export type ComponentSummary = {
	/**  Stable identifier. */
	id: string,
	/**  Display name. */
	name: string,
	/**  Grouping for the UI. */
	kind: ComponentKind,
	/**  One-line description. */
	summary: string,
	/**  Project homepage. */
	homepage: string,
	/**  Licence identifier. */
	license: string,
	/**  Whether several versions may coexist. */
	multi_version: boolean,
	/**  Caveat to show before installing, when there is one. */
	caveat: string | null,
	/**
	 *  Whether versions come from a fixed list rather than a live upstream.
	 * 
	 *  Pinned components cannot offer versions newer than the DevX catalog, so
	 *  the UI can explain why the list looks short.
	 */
	pinned: boolean,
};

/**  A version of a component that DevX can install. */
export type ComponentVersion = {
	/**  Component this version belongs to. */
	component_id: string,
	/**  Version string as published upstream, e.g. `8.4.25`. */
	version: string,
	/**  Release track. */
	channel: ReleaseChannel,
	/**  Release date as `YYYY-MM-DD`, when known. */
	released_at: string | null,
	/**  The artifact implementing this version. */
	artifact: Artifact,
};

/**
 *  Complete DevX configuration.
 * 
 *  Deliberately has no `#[serde(default)]`: every field is required on the wire
 *  so the generated TypeScript type has no optional properties. Robustness for
 *  partial or hand-edited files comes from [`merge_over_defaults`], which fills
 *  gaps before deserialization.
 */
export type Config = Config_Serialize | Config_Deserialize;

/**
 *  Complete DevX configuration.
 * 
 *  Deliberately has no `#[serde(default)]`: every field is required on the wire
 *  so the generated TypeScript type has no optional properties. Robustness for
 *  partial or hand-edited files comes from [`merge_over_defaults`], which fills
 *  gaps before deserialization.
 */
export type Config_Deserialize = {
	/**  Version of this document's schema. */
	schema_version: number,
	/**  Application-wide preferences. */
	general: General,
	/**  Networking and local domain settings. */
	network: Network,
	/**  Component download and installation behaviour. */
	provisioning: Provisioning,
	/**  FastCGI worker counts per installed PHP version. */
	php_pools: { [key in string]: number },
	/**  Enabled PHP extensions per installed PHP version. */
	php_extensions: { [key in string]: string[] },
	/**  Xdebug settings per installed PHP version. */
	php_xdebug: { [key in string]: XdebugConfig },
	/**  Resource limits per installed PHP version. */
	php_limits: { [key in string]: LimitConfig },
	/**  Custom port assignments per service. */
	service_ports: { [key in string]: number },
	/**  User-configured local sites. */
	sites: Site_Deserialize[],
	/**  User-configured supervised worker processes. */
	workers: Worker[],
	/**  User-configured scheduled tasks. */
	cron: CronJob[],
	/**  User-registered project folders with per-project preferences. */
	projects: ProjectSettings[],
};

/**
 *  Complete DevX configuration.
 * 
 *  Deliberately has no `#[serde(default)]`: every field is required on the wire
 *  so the generated TypeScript type has no optional properties. Robustness for
 *  partial or hand-edited files comes from [`merge_over_defaults`], which fills
 *  gaps before deserialization.
 */
export type Config_Serialize = {
	/**  Version of this document's schema. */
	schema_version: number,
	/**  Application-wide preferences. */
	general: General,
	/**  Networking and local domain settings. */
	network: Network,
	/**  Component download and installation behaviour. */
	provisioning: Provisioning,
	/**  FastCGI worker counts per installed PHP version. */
	php_pools: { [key in string]: number },
	/**  Enabled PHP extensions per installed PHP version. */
	php_extensions: { [key in string]: string[] },
	/**  Xdebug settings per installed PHP version. */
	php_xdebug: { [key in string]: XdebugConfig },
	/**  Resource limits per installed PHP version. */
	php_limits: { [key in string]: LimitConfig },
	/**  Custom port assignments per service. */
	service_ports: { [key in string]: number },
	/**  User-configured local sites. */
	sites: Site_Serialize[],
	/**  User-configured supervised worker processes. */
	workers: Worker[],
	/**  User-configured scheduled tasks. */
	cron: CronJob[],
	/**  User-registered project folders with per-project preferences. */
	projects: ProjectSettings[],
};

/**  How to reach one database server. */
export type ConnectionParams = {
	/**  Which engine speaks on the other end. */
	engine: Engine,
	/**  Host, almost always `127.0.0.1` for supervised services. */
	host: string,
	/**  Port from the service's port allocation. */
	port: number,
	/**
	 *  Username; DevX services use `root` / `postgres` with no password by
	 *  default, so the field is optional.
	 */
	username: string | null,
	/**  Password, same story as the username. */
	password: string | null,
	/**  Optional database/schema to scope table listings to. */
	database: string | null,
};

/**
 *  One user-configured scheduled task, run by Windows every N minutes.
 * 
 *  Stored under `[[cron]]`. The shape mirrors [`Worker`] minus instances —
 *  a scheduled run is a one-shot command, not a supervised process — with
 *  `every_minutes` driving the Windows task's `/SC MINUTE /MO` interval.
 */
export type CronJob = {
	/**  Unique short name, prefixed `DevX` in the Windows task list. */
	name: string,
	/**  Executable to run, when not using a DevX-managed PHP version. */
	program: string | null,
	/**  PHP version whose `php.exe` runs the task, when using one. */
	php_version: string | null,
	/**  Arguments passed to the program. */
	args: string[],
	/**  Absolute path the task runs in. */
	working_dir: string,
	/**  Minutes between runs, 1..=10080 (a week). */
	every_minutes: number,
};

/**  One scheduled task, as the UI shows it. */
export type CronStatus = {
	/**  The user-chosen task name (Windows task: `DevX <name>`). */
	name: string,
	/**  Program to run; a relative name runs off `PATH`. */
	program: string | null,
	/**  PHP version running the task, when DevX supplies the interpreter. */
	php_version: string | null,
	/**  Arguments passed to the program. */
	args: string[],
	/**  Directory the task runs in. */
	working_dir: string,
	/**  The interval in minutes. */
	every_minutes: number,
	/**  Whether the Windows scheduled task exists right now. */
	registered: boolean,
	/**
	 *  The Windows task's next scheduled run, as reported by `schtasks`.
	 * 
	 *  Raw text straight from the OS (locale-formatted); `null` when the task
	 *  is unregistered or the query failed, which the UI renders as "—".
	 */
	next_run: string | null,
};

/**  One column of a result set. */
export type DbColumn = {
	/**  Column name as the server reported it. */
	name: string,
};

/**  A tabular result: what the browser renders as a grid. */
export type DbResult = {
	/**  Column names, in order. */
	columns: DbColumn[],
	/**  Rows, each with one value per column. */
	rows: DbValue[][],
};

/**  A connectable database server, as the UI's connection picker sees it. */
export type DbServer = {
	/**  Engine behind the service. */
	engine: Engine,
	/**  Service id (`mariadb`, `postgresql`, `redis`). */
	service_id: string,
	/**  Host the service binds. */
	host: string,
	/**  Port from the service's allocation. */
	port: number,
	/**  Whether a TCP connection to the port succeeds right now. */
	reachable: boolean,
};

/**  A single cell of a result grid. */
export type DbValue = 
/**  SQL NULL — displayed distinctly from an empty string. */
"null" | 
/**
 *  An integer.
 * 
 *  Exported to TypeScript as a plain `number`. Specta forbids `i64` by
 *  default because JSON parsing truncates past 2^53; a display grid shows
 *  values as text, so the worst case is a rare cosmetic rounding on
 *  absurdly large values.
 */
({ int: number }) & { float?: never; other?: never; text?: never } | 
/**  A float. */
({ float: number | null }) & { int?: never; other?: never; text?: never } | 
/**  Bytes or text; the browser shows text. */
({ text: string }) & { float?: never; int?: never; other?: never } | 
/**  Anything else, rendered as the server's textual form. */
({ other: string }) & { float?: never; int?: never; text?: never };

/**
 *  A DevX error: a classification, a message, and optional operator guidance.
 * 
 *  Renamed for TypeScript so the generated binding does not shadow the global
 *  `Error`. `hint` is always serialized (rather than skipped when absent) to
 *  keep a single shape on the wire.
 */
export type DevxError = {
	/**  Machine-readable classification. */
	code: ErrorCode,
	/**  Human-readable description of what went wrong. */
	message: string,
	/**  Optional actionable next step shown to the user. */
	hint: string | null,
};

/**  Disk use of one managed directory, for the UI. */
export type DirUsage = {
	/**  What the directory holds (`runtimes`, `service data`, `logs`, `backups`). */
	label: string,
	/**  Total size on disk, in bytes. */
	size_bytes: number,
};

/**  How local domains are resolved. */
export type DnsMode = 
/**
 *  Prefer the bundled resolver with an NRPT rule, fall back to the hosts
 *  file when port 53 is unavailable.
 */
"auto" | 
/**  Always use the bundled resolver plus an NRPT rule. */
"resolver" | 
/**  Always write one hosts-file entry per site. No wildcard subdomains. */
"hosts_file";

/**  The bundled DNS resolver's status, for the UI. */
export type DnsStatus = {
	/**  Whether the resolver is running inside DevX right now. */
	running: boolean,
	/**  Port the resolver listens on, when running. */
	port: number | null,
	/**
	 *  Whether the NRPT rule routes `.test` queries to DevX. `None` when
	 *  the privileged helper is unavailable to check.
	 */
	nrpt_active: boolean | null,
	/**  The suffix the resolver answers for. */
	suffix: string,
};

/**  Full diagnostic report. */
export type DoctorReport = {
	/**  Worst status across all checks. */
	status: CheckStatus,
	/**  Individual results, in display order. */
	checks: Check[],
};

/**  Supported engines. */
export type Engine = 
/**  MariaDB or MySQL, both speak the MySQL protocol. */
"maria_db" | 
/**  PostgreSQL. */
"postgre_sql" | 
/**  Redis (and Redis-compatible servers). */
"redis";

/**
 *  Stable, machine-readable error classification.
 * 
 *  The string form is part of the IPC contract with the frontend; do not rename
 *  variants without updating the UI.
 */
export type ErrorCode = 
/**  Input failed validation before any side effect was attempted. */
"invalid_input" | 
/**  A required file, directory, component or record does not exist. */
"not_found" | 
/**  The requested change conflicts with existing state. */
"conflict" | 
/**  Filesystem-level failure. */
"io" | 
/**  Configuration could not be read, parsed or migrated. */
"config" | 
/**  Network failure while talking to an upstream service. */
"network" | 
/**  A downloaded artifact failed integrity verification. */
"integrity" | 
/**  Failure while starting, stopping or supervising a process. */
"process" | 
/**  The privileged helper is unavailable or refused the request. */
"privileged" | 
/**  Something failed that we could not classify. */
"internal";

/**  One recorded service transition from the persistent event log, for the UI. */
export type EventEntry = {
	/**  Unix timestamp in seconds. */
	at_unix: number,
	/**  Id of the supervised service. */
	id: string,
	/**  The state it moved to (`running`, `failed`, `starting`, …). */
	state: string,
	/**  Why it left the running state (`crashed`, `health_timeout`, …), when it did. */
	exit: string | null,
};

/**  Why a service left the `Running` or `Starting` state. */
export type ExitReason = 
/**  A stop was requested and the process exited. */
{ kind: "requested" } | 
/**  The process exited on its own, with this code. */
{ kind: "crashed"; 
/**  Process exit code, when known. */
code: number | null } | 
/**  The health check never passed within the allowed time. */
{ kind: "health_timeout" } | 
/**  The process could not be spawned at all. */
{ kind: "spawn_failed"; 
/**  Human-readable reason. */
message: string };

/**  Application-wide preferences. */
export type General = {
	/**  UI colour scheme. */
	theme: Theme,
	/**  Launch DevX when the user signs in. */
	start_with_windows: boolean,
	/**  Closing the window hides it to the tray instead of exiting. */
	close_to_tray: boolean,
	/**  Start services that were running when DevX last exited. */
	restore_services_on_start: boolean,
	/**  Send a Windows notification when a service fails. */
	notify_on_failure: boolean,
};

/**
 *  One `hosts`-file mapping, validated before it is ever applied.
 * 
 *  Inetpub-style attacks and cache poisoning start with a hostile hosts file,
 *  so both fields are validated in [`HostsEntry::validate`] and again at the
 *  helper boundary: a request that fails validation is never written.
 */
export type HostsEntry = {
	/**
	 *  Host name to map, e.g. `myapp.test`. Single DNS label or FQDN of
	 *  letters, digits and hyphens.
	 */
	hostname: string,
	/**  IP address the host name resolves to, e.g. `127.0.0.1`. */
	ip: string,
};

/**
 *  What a hosts re-sync produced: the fresh list plus the names it could
 *  not write.
 */
export type HostsResyncResult = {
	/**  Managed entries as they stand after the change. */
	entries: HostsEntry[],
	/**
	 *  Site names that were skipped, with reasons. A name owned by a
	 *  hand-written (foreign) hosts line is refused rather than shadowed —
	 *  remove that line by hand, then re-sync.
	 */
	skipped: HostsSkipped[],
};

/**
 *  Re-syncs everything name resolution needs after a (re)start: server
 *  blocks, hosts-file entries, resolver cache flush, and the bundled
 *  resolver's hostname map.
 * 
 *  Blocks alone are not enough: after an update changes binds or certs, the
 *  hosts file may still point at the previous address (bare URL refused
 *  while `:port` works). Best-effort throughout; failures only warn.
 *  One site name the hosts re-sync could not write, with the reason.
 */
export type HostsSkipped = {
	/**  Host name that was not written. */
	hostname: string,
	/**  Why, e.g. a conflicting hand-written line owns the name. */
	reason: string,
};

/**
 *  Where an install currently is, mirrored from
 *  [`devx_provision::InstallStage`] into an IPC-friendly shape.
 */
export type InstallPhase = 
/**  Resolving a separately-published checksum. */
{ stage: "resolving_checksum" } | 
/**  Downloading, with byte counts. */
{ stage: "downloading"; 
/**  Bytes fetched so far. */
downloaded: number; 
/**  Total bytes, when the server reports a length. */
total: number | null } | 
/**  Verifying the SHA-256. */
{ stage: "verifying" } | 
/**  Extracting the archive. */
{ stage: "extracting" } | 
/**  Promoting the staged directory into place. */
{ stage: "finalising" } | 
/**  Complete. */
{ stage: "done" };

/**
 *  Progress of a component installation.
 * 
 *  One install emits a stream of these, keyed by `component_id` and `version`
 *  so the UI can route them to the right row when several run at once.
 */
export type InstallProgress = {
	/**  Component being installed. */
	component_id: string,
	/**  Version being installed. */
	version: string,
	/**  Current phase. */
	phase: InstallPhase,
};

/**  A version of a component that is installed on disk. */
export type InstalledVersion = {
	/**  Component identifier. */
	component_id: string,
	/**  Installed version string. */
	version: string,
	/**  Absolute install directory. */
	path: string,
};

/**  One version's resource limits as ini values. */
export type LimitConfig = {
	/**  `memory_limit` ini value, e.g. `256M`. */
	memory_limit?: string,
	/**  `upload_max_filesize` ini value, e.g. `64M`. */
	upload_max_filesize?: string,
	/**  `max_execution_time` in seconds. */
	max_execution_time?: number,
	/**  Whether the Zend OPcache loads. */
	opcache_enabled?: boolean,
};

/**  One captured log line, for the UI tail. */
export type LogEntry = {
	/**  Monotonic sequence number. */
	seq: number,
	/**  Which stream it came from. */
	stream: LogStream,
	/**  Line text. */
	text: string,
};

/**  The tail of one log file, for the log viewer. */
export type LogFileContent = {
	/**  The file that was read. */
	file_name: string,
	/**  Last `tail` lines, in file order. */
	lines: string[],
	/**  Whether the file has more lines than were returned. */
	truncated: boolean,
};

/**  One log file in the DevX logs directory, for the log viewer. */
export type LogFileInfo = {
	/**  File name inside the logs directory, e.g. `nginx.log.1`. */
	file_name: string,
	/**  Service the log belongs to (`nginx`, `php-pool-8.4.25`, …). */
	service_id: string,
	/**  Whether this is a rotated (previous-generation) file. */
	rotated: boolean,
	/**  Size on disk, in bytes. */
	size_bytes: number,
	/**  Last modification as Unix seconds; `null` when unavailable. */
	modified_unix: number | null,
};

/**  Which standard stream a line came from. */
export type LogStream = 
/**  Standard output. */
"stdout" | 
/**  Standard error. */
"stderr";

/**  Status of the Mailpit service, as the Mail page needs it. */
export type MailStatus = {
	/**  Whether the `mailpit` service is currently running. */
	running: boolean,
	/**  Port the HTTP UI (and API) answers on; `null` while stopped. */
	port: number | null,
	/**  SMTP port apps should send mail to. */
	smtp_port: number,
	/**
	 *  Total and unread counts, when the API is reachable right now.
	 * 
	 *  Exported to TypeScript as plain `number`s (see the repo-wide `u64`
	 *  note); `null` while the API is unreachable.
	 */
	total: number | null,
	/**  Unread count, when the API is reachable right now. */
	unread: number | null,
};

/**  A full message (`GET /api/v1/message/{id}`): summary fields plus body. */
export type Message = {
	/**  Mailpit's short database ID. */
	id: string,
	/**  Sender. */
	from: Address,
	/**  Primary recipients. */
	to: Address[],
	/**  CC recipients. */
	cc: Address[],
	/**  BCC recipients. */
	bcc: Address[],
	/**  Subject line. */
	subject: string,
	/**  Message date, falling back to receive time (RFC 3339). */
	date: string,
	/**  Plain-text body, when the message has one. */
	text: string | null,
	/**  HTML body, when the message has one. */
	html: string | null,
	/**
	 *  Size of the raw message in bytes.
	 * 
	 *  Exported to TypeScript as a plain `number`; see the repo-wide note on
	 *  `u64` fields — display values never approach 2^53.
	 */
	size: number,
	/**  Tags Mailpit attached to the message. */
	tags: string[],
	/**  Attachments, metadata only (bytes stay in Mailpit). */
	attachments: Attachment[],
};

/**  One message in the inbox listing (`GET /api/v1/messages`). */
export type MessageSummary = {
	/**  Mailpit's short database ID; the key for every other call. */
	id: string,
	/**  Whether the message has been read (viewed) already. */
	read: boolean,
	/**  Sender. */
	from: Address,
	/**  Primary recipients. */
	to: Address[],
	/**  Subject line, possibly empty. */
	subject: string,
	/**  When the message was received (RFC 3339). */
	created: string,
	/**
	 *  Size of the raw message in bytes.
	 * 
	 *  Exported to TypeScript as a plain `number`; see the repo-wide note on
	 *  `u64` fields — display values never approach 2^53.
	 */
	size: number,
	/**  How many attachments the message carries. */
	attachments: number,
	/**  Up to 250 characters of plain-text preview. */
	snippet: string,
	/**  Tags Mailpit attached to the message. */
	tags: string[],
};

/**  Networking and local domain settings. */
export type Network = {
	/**
	 *  Suffix for local sites, without a leading dot. `test` is reserved by
	 *  RFC 6761 for exactly this purpose and never resolves publicly.
	 */
	domain_suffix: string,
	/**  Port the local web server listens on for HTTP. */
	http_port: number,
	/**  Port the local web server listens on for HTTPS. */
	https_port: number,
	/**  Port the bundled DNS resolver binds to. */
	dns_port: number,
	/**  Strategy used to resolve local domains. */
	dns_mode: DnsMode,
};

/**  One notification: a recorded transition, with what §98 shows beside it. */
export type NotificationEntry = {
	/**  Unix timestamp in seconds. */
	at_unix: number,
	/**  Id of the supervised service. */
	id: string,
	/**  The state it moved to (`running`, `failed`, `starting`, …). */
	state: string,
	/**  Why it left the running state (`crashed`, `health_timeout`, …), when it did. */
	exit: string | null,
	/**
	 *  `error` for the transitions that stay until acknowledged, `info`
	 *  otherwise. The frontend pairs it with text, never with colour alone
	 *  (§55).
	 */
	severity: string,
	/**  Whether the user still owes this one a look. */
	unread: boolean,
};

/**  §98's panel contents. */
export type NotificationList = {
	/**  The entries to show, newest first. */
	entries: NotificationEntry[],
	/**
	 *  How many of the events read are unread — the bell's badge.
	 * 
	 *  Counted over every event handed in, not just the ones that fit in
	 *  `entries`, so a truncated panel still badges the truth.
	 */
	unread_count: number,
	/**
	 *  How many recorded transitions this answer was computed from.
	 * 
	 *  Not shown as a number: it is what lets the panel tell "nothing has
	 *  happened yet" from "everything was cleared" instead of printing one
	 *  sentence for both.
	 */
	recorded: number,
};

/**  The PHP extensions a version ships and which are enabled, for the UI. */
export type PhpExtensionInfo = {
	/**  PHP version these extensions belong to. */
	version: string,
	/**  Every extension DLL the installed version ships, sorted. */
	installed: string[],
	/**  Extension DLLs currently enabled for the version. */
	enabled: string[],
};

/**  A summary of one PHP FastCGI pool, including its live state. */
export type PhpPoolStatus = {
	/**  Pool identifier (`php-pool-8.4.25`). */
	id: string,
	/**  PHP version served by this pool. */
	version: string,
	/**  FastCGI workers configured for the pool. */
	workers: number,
	/**  Port the pool's FastCGI socket binds to. */
	port: number,
	/**  Current lifecycle state. */
	state: ServiceState,
};

/**  The Xdebug state of one PHP version, for the UI. */
export type PhpXdebugInfo = {
	/**  PHP version this configuration belongs to. */
	version: string,
	/**  Whether Xdebug is configured for this version at all. */
	enabled: boolean,
	/**  Xdebug mode set (`off`, `debug`, `develop,debug`, …); empty when unconfigured. */
	mode: string,
	/**  The IDE port the debugger connects back to. */
	client_port: number,
};

/**  One claimed port and its owner, for the UI. */
export type PortEntry = {
	/**  What listens on the port (`nginx`, `php-pool-8.4.25`, `Mailpit`, …). */
	owner: string,
	/**  The port number. */
	port: number,
	/**  Whether the service is running right now. */
	active: boolean,
};

/**  A process listening on a local TCP port. */
export type PortOwner = {
	/**  The port being listened on. */
	port: number,
	/**  PID of the owning process. */
	pid: number,
	/**  Best-effort process image name (e.g. `nginx.exe`), if resolvable. */
	process_name: string | null,
};

/**  How the privileged helper looks from this machine right now. */
export type PrivilegedStatus = {
	/**  Whether the helper's named pipe answered. */
	available: boolean,
	/**  Protocol version of a reachable helper, when it answered. */
	protocol_version: number | null,
};

/**  One saved configuration profile. */
export type ProfileEntry = {
	/**  Profile name, also the file stem on disk. */
	name: string,
	/**  Last modification as Unix seconds; `null` when unavailable. */
	modified_unix: number | null,
};

/**
 *  A user-registered project folder, with per-project preferences.
 * 
 *  Stored under `[[projects]]`. Registration is what makes a project show up
 *  on the Projects page before any site or worker points into it; the
 *  runtime defaults are preferences shown and applied by the UI layer, not
 *  enforced by the config parser.
 */
export type ProjectSettings = {
	/**  Absolute folder path on disk; unique (case-insensitively). */
	path: string,
	/**  Optional display name; defaults to the folder name. */
	label: string | null,
	/**  Preferred PHP version, e.g. `8.4.25`; `None` means the global default. */
	default_php: string | null,
	/**  Preferred Node.js version; `None` means the global default. */
	default_node: string | null,
	/**  Preferred Python version; `None` means the global default. */
	default_python: string | null,
	/**  Environment variables applied to this project's processes. */
	env: { [key in string]: string },
};

/**  One folder-grouped project, as the UI shows it. */
export type ProjectSummary = {
	/**  Folder name, e.g. `myapp`. */
	name: string,
	/**  Absolute folder path. */
	path: string,
	/**
	 *  Whether the project was explicitly registered by the user (vs derived
	 *  from sites/workers that merely point into the folder).
	 */
	managed: boolean,
	/**  Optional display label from the registered settings. */
	label: string | null,
	/**  Sites whose docroot lives under this folder. */
	sites: SiteStatus[],
	/**  Workers whose working directory lives under this folder. */
	workers: WorkerStatus[],
	/**  Scheduled tasks whose working directory lives under this folder. */
	cron: CronStatus[],
	/**  PHP versions the project's sites and workers use, sorted. */
	php_versions: string[],
	/**  Registered default PHP version for the project, when set. */
	default_php: string | null,
	/**  Registered default Node.js version for the project, when set. */
	default_node: string | null,
	/**  Registered default Python version for the project, when set. */
	default_python: string | null,
	/**
	 *  How many supervised things belonging to the project are running
	 *  (worker instances plus cron-adjacent services).
	 */
	running_workers: number,
	/**  How many worker instances are configured in total. */
	total_workers: number,
};

/**  Component download and installation behaviour. */
export type Provisioning = {
	/**  Catalog describing components, versions and artifact hashes. */
	catalog_url: string,
	/**  Keep downloaded archives after a successful install. */
	keep_archives: boolean,
	/**  Maximum simultaneous downloads. */
	max_concurrent_downloads: number,
	/**  Refresh version metadata automatically on startup. */
	auto_refresh_catalog: boolean,
};

/**  Release track a version belongs to. */
export type ReleaseChannel = 
/**  Long-term support release, preferred default where upstream defines one. */
"lts" | 
/**  Current stable release. */
"stable" | 
/**  Pre-release, only offered when the catalog opts in. */
"prerelease";

/**
 *  A state transition announced by a supervisor.
 * 
 *  Published on a registry-wide broadcast channel so a single subscriber can
 *  observe every service at once; `exit` carries why the service left the
 *  running state, when it did.
 */
export type ServiceEvent = {
	/**  Id of the supervised service. */
	id: string,
	/**  The state it moved to. */
	state: ServiceState,
	/**  Why it left the running state, if it did. */
	exit: ExitReason | null,
};

/**
 *  A state transition of a supervised service.
 * 
 *  Mirrors [`devx_proc::ServiceEvent`] so the frontend can update status
 *  badges and log tails the moment something happens instead of waiting for
 *  the next poll.
 */
export type ServiceEventUpdate = {
	/**  The transition. */
	event: ServiceEvent,
};

/**  Point-in-time resource use of one supervised service. */
export type ServiceMetrics = {
	/**  Id of the supervised service. */
	id: string,
	/**  Current lifecycle state. */
	state: ServiceState,
	/**  CPU use since the previous sample, normalised to one core (0–100). */
	cpu_percent: number | null,
	/**  Resident memory of every process in the service's job, in bytes. */
	memory_bytes: number,
	/**  How many live processes the job contains. */
	processes: number,
};

/**  Where a supervised service is in its lifecycle. */
export type ServiceState = 
/**  Not running, and not trying to. */
"stopped" | 
/**  Spawned, waiting for its health check to pass. */
"starting" | 
/**  Running and healthy. */
"running" | 
/**  Asked to stop, waiting for the process to exit. */
"stopping" | 
/**  Exited unexpectedly, or failed to start. */
"failed";

/**  Status of a supervised service, for the UI. */
export type ServiceStatus = {
	/**  Service identifier. */
	id: string,
	/**  Current lifecycle state. */
	state: ServiceState,
};

/**
 *  One user-configured site.
 * 
 *  Stored in `config.toml` under `[[sites]]`; rendered into web-server site
 *  blocks by `devx-provision::sites` whenever the configuration changes.
 */
export type Site = Site_Serialize | Site_Deserialize;

/**  Basic-auth credentials for one site. */
export type SiteAuth = {
	/**  User name accepted by the site. */
	username: string,
	/**
	 *  htpasswd-format password hash (apr1/bcrypt); nginx and Caddy both
	 *  read this format.
	 */
	password_hash: string,
};

/**  Result of one site health check, as the UI shows it. */
export type SitePing = {
	/**  HTTP status code, when the server answered. */
	status: number | null,
	/**  Total round-trip time in milliseconds, when the server answered. */
	latency_ms: number | null,
	/**  What went wrong, when the check failed. */
	error: string | null,
};

/**  One parsed request from a site's access log, for the inspector. */
export type SiteRequestEntry = {
	/**
	 *  Unix seconds of the request; `null` when the log line carries no
	 *  parsable timestamp.
	 */
	time_unix: number | null,
	/**  Remote address as logged (usually `127.0.0.1`). */
	remote: string,
	/**  HTTP method, e.g. `GET`. */
	method: string,
	/**  Request path including query string, e.g. `/index.php?page=2`. */
	path: string,
	/**  HTTP status the server answered with. */
	status: number,
	/**  Response body size in bytes, when logged; `null` for 0/`-`. */
	bytes: number | null,
	/**  `Referer` header when present. */
	referer: string,
	/**  `User-Agent` header when present. */
	user_agent: string,
	/**  Milliseconds the server spent on the request, when the log records it. */
	duration_ms: number | null,
};

/**  One site as the UI sees it, with the resolved FastCGI endpoint. */
export type SiteStatus = {
	/**  Host name served. */
	hostname: string,
	/**  Absolute docroot path. */
	docroot: string,
	/**  PHP version serving the site, empty for a static site. */
	php_version: string,
	/**  The `fastcgi_pass` endpoint, when the site runs PHP. */
	php_endpoint: string | null,
	/**  Whether the site is served over HTTPS with the local CA certificate. */
	https: boolean,
	/**  Which web server serves this site. */
	web_server: WebServer,
	/**  Environment variables exposed to the site's PHP requests. */
	env: { [key in string]: string },
	/**  Additional host names the site answers to. */
	aliases: string[],
	/**  Basic-auth user when the site is protected, `None` for public. */
	auth: SiteAuth | null,
	/**
	 *  HTTP port of the owning web server (80 on its own loopback by
	 *  default).
	 */
	port: number,
	/**
	 *  HTTPS port of the owning web server (443 on its own loopback by
	 *  default).
	 */
	https_port: number,
	/**
	 *  Public URL of the site: bare when the owner binds 80/443 on its own
	 *  loopback, otherwise the direct `:port` URL.
	 */
	url: string,
};

/**
 *  One user-configured site.
 * 
 *  Stored in `config.toml` under `[[sites]]`; rendered into web-server site
 *  blocks by `devx-provision::sites` whenever the configuration changes.
 */
export type Site_Deserialize = {
	/**  Host name served, e.g. `myapp.test`. */
	hostname: string,
	/**  Absolute path of the folder nginx serves. */
	docroot: string,
	/**  PHP version whose pool serves the site, empty for a static site. */
	php_version: string,
	/**  Serve the site over HTTPS with the local CA's certificate. */
	https?: boolean,
	/**
	 *  Which installed web server serves the site. Defaults to nginx, the
	 *  historical choice, so configs written before the field existed load
	 *  unchanged.
	 */
	web_server?: WebServer,
	/**
	 *  Environment variables passed to the site's PHP requests, rendered as
	 *  `fastcgi_param` lines in the site's nginx block. Static sites ignore
	 *  them.
	 */
	env?: { [key in string]: string },
	/**
	 *  Additional host names the site answers to, rendered into the nginx
	 *  `server_name` list. Subdomain wildcards are covered by the resolver.
	 */
	aliases?: string[],
	/**
	 *  HTTP Basic Auth credentials for the whole site. `None` (or an empty
	 *  user) means the site is public. Passwords are stored as bcrypt-style
	 *  htpasswd hashes, never as plain text.
	 */
	auth?: SiteAuth | null,
};

/**
 *  One user-configured site.
 * 
 *  Stored in `config.toml` under `[[sites]]`; rendered into web-server site
 *  blocks by `devx-provision::sites` whenever the configuration changes.
 */
export type Site_Serialize = {
	/**  Host name served, e.g. `myapp.test`. */
	hostname: string,
	/**  Absolute path of the folder nginx serves. */
	docroot: string,
	/**  PHP version whose pool serves the site, empty for a static site. */
	php_version: string,
	/**  Serve the site over HTTPS with the local CA's certificate. */
	https: boolean,
	/**
	 *  Which installed web server serves the site. Defaults to nginx, the
	 *  historical choice, so configs written before the field existed load
	 *  unchanged.
	 */
	web_server: WebServer,
	/**
	 *  Environment variables passed to the site's PHP requests, rendered as
	 *  `fastcgi_param` lines in the site's nginx block. Static sites ignore
	 *  them.
	 */
	env: { [key in string]: string },
	/**
	 *  Additional host names the site answers to, rendered into the nginx
	 *  `server_name` list. Subdomain wildcards are covered by the resolver.
	 */
	aliases: string[],
	/**
	 *  HTTP Basic Auth credentials for the whole site. `None` (or an empty
	 *  user) means the site is public. Passwords are stored as bcrypt-style
	 *  htpasswd hashes, never as plain text.
	 */
	auth?: SiteAuth | null,
};

/**  The result of scaffolding a site from a template. */
export type TemplateCreateResult = {
	/**  The site that was created. */
	hostname: string,
	/**  The suggested terminal command, when the template delegates to one. */
	follow_up_command: string | null,
};

/**  One scaffoldable site template, for the UI. */
export type TemplateInfo = {
	/**  Template identifier. */
	id: string,
	/**  Display name. */
	name: string,
	/**  What the template sets up. */
	description: string,
	/**  Whether the files are generated locally, without downloading. */
	local: boolean,
};

/**  One terminal run's exit information. */
export type TerminalExit = {
	/**  Which run this belongs to, matching the streamed `TerminalOutput`s. */
	run_id: number,
	/**  Exit code, when the process ended normally. */
	code: number | null,
};

/**
 *  One chunk of output from a terminal command run.
 * 
 *  The backend streams lines as they are written instead of returning the
 *  whole output at the end, so long-running commands feel live.
 */
export type TerminalOutput = {
	/**  Which run the line belongs to. */
	run_id: number,
	/**  Which stream it came from: `out` or `err`. */
	stream: string,
	/**  The line text, without its newline. */
	text: string,
};

/**  UI colour scheme. */
export type Theme = 
/**  Follow the Windows setting. */
"system" | 
/**  Always light. */
"light" | 
/**  Always dark. */
"dark";

/**  Status of one site's public share, as the UI shows it. */
export type TunnelStatus = {
	/**  The shared site's local host name. */
	hostname: string,
	/**  Whether the cloudflared process is running. */
	running: boolean,
	/**
	 *  The public `https://…trycloudflare.com` URL, once assigned.
	 * 
	 *  Cloudflare announces it on stdout shortly after start, so this is
	 *  `null` for a few seconds after `tunnel_start`.
	 */
	url: string | null,
};

/**  Whether a newer DevX release is available upstream. */
export type UpdateStatus = {
	/**  Version of the running build. */
	current: string,
	/**  Newest release tag upstream, when one could be resolved. */
	latest: string | null,
	/**  Whether `latest` is newer than `current`. */
	update_available: boolean,
	/**  Release page for the new version, when known. */
	url: string | null,
};

/**  Result of listing versions, including whether the data was stale. */
export type VersionListing = {
	/**  Versions, newest first. */
	versions: ComponentVersion[],
	/**  Whether the underlying metadata came from a stale cache. */
	stale: boolean,
	/**  Versions that were skipped because no checksum is published for them. */
	unverifiable: string[],
};

/**  The web server that serves a site. */
export type WebServer = 
/**
 *  nginx — the default, and the only server with a rendered sites include
 *  before this field existed.
 */
"Nginx" | 
/**  Apache — classic web server with .htaccess support. */
"Apache" | 
/**  Caddy — minimal config, HTTP/2 and HTTP/3 out of the box. */
"Caddy" | 
/**  FrankenPHP — serves PHP directly, no FastCGI pool needed. */
"FrankenPhp";

/**
 *  One user-configured supervised worker process.
 * 
 *  Stored under `[[workers]]`. Either `program` (a path or a name on `PATH`)
 *  or `php_version` (runs that installed version's `php.exe`) must be set —
 *  never both — and `instances` identical copies run side by side, each its
 *  own supervised process.
 */
export type Worker = {
	/**  Unique short name, also used to build the service id. */
	name: string,
	/**  Executable to run, when not using a DevX-managed PHP version. */
	program: string | null,
	/**  PHP version whose `php.exe` runs the worker, when using one. */
	php_version: string | null,
	/**  Arguments passed to the program. */
	args: string[],
	/**  Absolute path the process runs in. */
	working_dir: string,
	/**  How many copies to run. */
	instances: number,
};

/**  One supervised worker instance, as the UI shows it. */
export type WorkerInstanceStatus = {
	/**  Supervisor id: `worker-<name>-<instance>`. */
	id: string,
	/**  Current lifecycle state. */
	state: ServiceState,
};

/**  One configured worker with the live state of its instances. */
export type WorkerStatus = {
	/**  The user-chosen worker name. */
	name: string,
	/**  Program to run; a relative name runs off `PATH`. */
	program: string | null,
	/**  PHP version running the worker, when DevX supplies the interpreter. */
	php_version: string | null,
	/**  Arguments passed to the program. */
	args: string[],
	/**  Directory the process runs in. */
	working_dir: string,
	/**  How many instances are configured. */
	instances: number,
	/**  Live state of each instance that has been started. */
	live: WorkerInstanceStatus[],
};

/**
 *  Xdebug 3 knobs for one PHP version's pool.
 * 
 *  `mode` accepts Xdebug's own mode words (`off`, `develop`, `debug`,
 *  `coverage`, `gcstats`, `profile`, `trace`, comma-separated combinations);
 *  `client_port` is the IDE's listening port. Kept as strings rather than an
 *  enum so any future mode word works without a DevX release.
 */
export type XdebugConfig = {
	/**  Xdebug mode set (`off`, `debug`, `develop,debug`, …). */
	mode?: string,
	/**  The IDE port Xdebug connects back to (9003 by default upstream). */
	client_port?: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

